DROP TABLE "alcohol_tests" CASCADE;--> statement-breakpoint
DROP TABLE "behavioral_observations" CASCADE;--> statement-breakpoint
DROP TABLE "committee_agreements" CASCADE;--> statement-breakpoint
DROP TABLE "committee_meetings" CASCADE;--> statement-breakpoint
DROP TABLE "committee_members" CASCADE;--> statement-breakpoint
DROP TABLE "committees" CASCADE;--> statement-breakpoint
DROP TABLE "contractor_documents" CASCADE;--> statement-breakpoint
DROP TABLE "contractor_workers" CASCADE;--> statement-breakpoint
DROP TABLE "contractors" CASCADE;--> statement-breakpoint
DROP TABLE "document_deliveries" CASCADE;--> statement-breakpoint
DROP TABLE "document_signatures" CASCADE;--> statement-breakpoint
DROP TABLE "emergency_drills" CASCADE;--> statement-breakpoint
DROP TABLE "emergency_equipment" CASCADE;--> statement-breakpoint
DROP TABLE "emergency_plans" CASCADE;--> statement-breakpoint
DROP TABLE "emergency_teams" CASCADE;--> statement-breakpoint
DROP TABLE "epp_lifecycle_policies" CASCADE;--> statement-breakpoint
DROP TABLE "epp_position_matrix" CASCADE;--> statement-breakpoint
DROP TABLE "epp_recambio_log" CASCADE;--> statement-breakpoint
DROP TABLE "epp_stock_thresholds" CASCADE;--> statement-breakpoint
DROP TABLE "equipment_checklists" CASCADE;--> statement-breakpoint
DROP TABLE "equipment_daily_reports" CASCADE;--> statement-breakpoint
DROP TABLE "equipment_inspections" CASCADE;--> statement-breakpoint
DROP TABLE "equipment_report_reviews" CASCADE;--> statement-breakpoint
DROP TABLE "health_aptitudes" CASCADE;--> statement-breakpoint
DROP TABLE "health_exams" CASCADE;--> statement-breakpoint
DROP TABLE "health_restrictions" CASCADE;--> statement-breakpoint
DROP TABLE "incident_corrective_followups" CASCADE;--> statement-breakpoint
DROP TABLE "incident_disseminations" CASCADE;--> statement-breakpoint
DROP TABLE "incident_investigations" CASCADE;--> statement-breakpoint
DROP TABLE "incident_notifications" CASCADE;--> statement-breakpoint
DROP TABLE "incident_statements" CASCADE;--> statement-breakpoint
DROP TABLE "inspection_items" CASCADE;--> statement-breakpoint
DROP TABLE "inspection_runs" CASCADE;--> statement-breakpoint
DROP TABLE "inspection_templates" CASCADE;--> statement-breakpoint
DROP TABLE "iper_matrices" CASCADE;--> statement-breakpoint
DROP TABLE "iper_risk_items" CASCADE;--> statement-breakpoint
DROP TABLE "kpi_snapshots" CASCADE;--> statement-breakpoint
DROP TABLE "labor_hours" CASCADE;--> statement-breakpoint
DROP TABLE "legal_document_versions" CASCADE;--> statement-breakpoint
DROP TABLE "legal_documents" CASCADE;--> statement-breakpoint
DROP TABLE "minsal_protocols" CASCADE;--> statement-breakpoint
DROP TABLE "permit_attachments" CASCADE;--> statement-breakpoint
DROP TABLE "permit_requests" CASCADE;--> statement-breakpoint
DROP TABLE "permit_signoffs" CASCADE;--> statement-breakpoint
DROP TABLE "permit_templates" CASCADE;--> statement-breakpoint
DROP TABLE "prevention_incident_actions" CASCADE;--> statement-breakpoint
DROP TABLE "prevention_incidents" CASCADE;--> statement-breakpoint
DROP TABLE "protocol_applications" CASCADE;--> statement-breakpoint
DROP TABLE "sanitization_controls" CASCADE;--> statement-breakpoint
DROP TABLE "training_courses" CASCADE;--> statement-breakpoint
DROP TABLE "worker_training_assignments" CASCADE;