-- The accompanying snapshot was generated by Drizzle Kit after the
-- hand-authored `0181`–`0183` DDL, so future schema generation starts from the
-- actual current state. This custom SQL remains limited to this request change.
ALTER TABLE "purchase_requests" ADD COLUMN "submission_key" text;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD COLUMN "submission_payload_hash" text;--> statement-breakpoint
CREATE UNIQUE INDEX "purchase_requests_requester_submission_key_unique"
  ON "purchase_requests" USING btree ("requester_id", "submission_key");
