/**
 * Authoring model for dates generated by a Preventive Program activity.
 *
 * This module deliberately works with civil ISO dates rather than `Date` at
 * the API boundary.  A schedule is a calendar contract, not an instant, so a
 * browser/server timezone must not move an occurrence to the previous day.
 */

import { pluralize } from "@/lib/utils"

export type PdtpScheduleDefinition =
  | { version: 1; kind: "one_time"; date: string }
  | {
      version: 1
      kind: "recurring"
      startDate: string
      endDate: string
      every: number
      unit: "day" | "week" | "month" | "year"
      weekdays?: number[]
      dayOfMonth?: number
      plannedQuantity?: number
    }
  | {
      version: 1
      kind: "event"
      triggerConnectorKey: string
      triggerEventKey: string
      dueValue: number
      dueUnit: "hour" | "day"
    }
  | { version: 1; kind: "on_demand"; dueValue: number; dueUnit: "hour" | "day" }
  | { version: 1; kind: "legacy_grid" }

export type PdtpIsoWeek = { isoWeekYear: number; isoWeek: number }

export type PdtpScheduledOccurrence = PdtpIsoWeek & {
  scheduledFor: string
  plannedQuantity: number
}

/**
 * Human-readable SLA used by the planning and obligation views.  Event and
 * on-demand activities may use either civil days or elapsed hours; keeping the
 * formatting next to the schedule contract avoids rendering an hour-based
 * activity as `null día(s)` in one of the legacy views.
 */
export function describePdtpDue(
  dueDays: number | null | undefined,
  dueHours: number | null | undefined,
): string | null {
  if (dueHours !== null && dueHours !== undefined) return `${dueHours} ${pluralize(dueHours, "hora")}`
  if (dueDays !== null && dueDays !== undefined) return `${dueDays} ${pluralize(dueDays, "día")}`
  return null
}

type CivilDateParts = { year: number; month: number; day: number }

const ISO_DATE_RE = /^(\d{4})-(\d{2})-(\d{2})$/

function parseCivilDate(value: string): CivilDateParts {
  const match = ISO_DATE_RE.exec(value)
  if (!match) throw new Error(`Fecha civil inválida: ${value}`)
  const year = Number(match[1])
  const month = Number(match[2])
  const day = Number(match[3])
  const candidate = new Date(Date.UTC(year, month - 1, day))
  if (candidate.getUTCFullYear() !== year || candidate.getUTCMonth() + 1 !== month || candidate.getUTCDate() !== day) {
    throw new Error(`Fecha civil inválida: ${value}`)
  }
  return { year, month, day }
}

function toUtcDate(parts: CivilDateParts): Date {
  return new Date(Date.UTC(parts.year, parts.month - 1, parts.day))
}

function toCivilDate(date: Date): string {
  return date.toISOString().slice(0, 10)
}

function daysInMonth(year: number, month: number): number {
  return new Date(Date.UTC(year, month, 0)).getUTCDate()
}

function addDays(date: Date, days: number): Date {
  const result = new Date(date)
  result.setUTCDate(result.getUTCDate() + days)
  return result
}

function addMonthsClamped(date: Date, months: number, dayOfMonth?: number): Date {
  const target = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + months, 1))
  const desiredDay = dayOfMonth ?? date.getUTCDate()
  target.setUTCDate(Math.min(Math.max(1, desiredDay), daysInMonth(target.getUTCFullYear(), target.getUTCMonth() + 1)))
  return target
}

function addYearsClamped(date: Date, years: number, dayOfMonth?: number): Date {
  return addMonthsClamped(date, years * 12, dayOfMonth)
}

function startOfIsoWeek(date: Date): Date {
  const weekday = date.getUTCDay() === 0 ? 7 : date.getUTCDay()
  return addDays(date, 1 - weekday)
}

/** Returns ISO-8601 week-year and week (Monday is day 1). */
export function getPdtpIsoWeek(value: string | Date): PdtpIsoWeek {
  const date = typeof value === "string" ? toUtcDate(parseCivilDate(value)) : new Date(value)
  const thursday = addDays(date, 4 - (date.getUTCDay() === 0 ? 7 : date.getUTCDay()))
  const isoWeekYear = thursday.getUTCFullYear()
  const firstThursday = new Date(Date.UTC(isoWeekYear, 0, 4))
  const diffDays = Math.floor((startOfIsoWeek(thursday).getTime() - startOfIsoWeek(firstThursday).getTime()) / 86_400_000)
  return { isoWeekYear, isoWeek: Math.floor(diffDays / 7) + 1 }
}

/** Lists the ISO weeks touched by any civil day of a calendar month. */
export function listPdtpIsoWeeksIntersectingMonth(year: number, month: number): PdtpIsoWeek[] {
  if (!Number.isInteger(year) || !Number.isInteger(month) || month < 1 || month > 12) throw new Error("Mes inválido.")
  const seen = new Set<string>()
  const result: PdtpIsoWeek[] = []
  const first = new Date(Date.UTC(year, month - 1, 1))
  const last = new Date(Date.UTC(year, month, 0))
  for (let cursor = first; cursor <= last; cursor = addDays(cursor, 1)) {
    const week = getPdtpIsoWeek(cursor)
    const key = `${week.isoWeekYear}-${week.isoWeek}`
    if (!seen.has(key)) {
      seen.add(key)
      result.push(week)
    }
  }
  return result
}

function occurrence(scheduledFor: string, plannedQuantity: number): PdtpScheduledOccurrence {
  return { scheduledFor, ...getPdtpIsoWeek(scheduledFor), plannedQuantity }
}

function clampRange(range: { startDate: string; endDate: string }): { start: Date; end: Date } {
  const start = toUtcDate(parseCivilDate(range.startDate))
  const end = toUtcDate(parseCivilDate(range.endDate))
  if (start > end) throw new Error("El período de programación es inválido.")
  return { start, end }
}

/**
 * Definiciones calendarizadas nuevas no pueden quedar parcialmente fuera del
 * período anual. La expansión sigue recibiendo un rango para leer datos
 * históricos y hacer el clamp defensivo, pero la escritura debe rechazar una
 * configuración que dejaría al usuario creyendo que programó una ocurrencia
 * que luego nunca se materializaría.
 */
export function assertPdtpScheduleDefinitionWithinPeriod(
  definition: PdtpScheduleDefinition | null | undefined,
  period: { startDate: string; endDate: string },
): void {
  if (!definition || definition.kind === "event" || definition.kind === "on_demand" || definition.kind === "legacy_grid") return
  const range = clampRange(period)
  if (definition.kind === "one_time") {
    const date = toUtcDate(parseCivilDate(definition.date))
    if (date < range.start || date > range.end) {
      throw new Error("La fecha planificada debe estar dentro del período del programa.")
    }
    return
  }

  const start = toUtcDate(parseCivilDate(definition.startDate))
  const end = toUtcDate(parseCivilDate(definition.endDate))
  if (start < range.start || end > range.end) {
    throw new Error("El rango de recurrencia debe estar dentro del período del programa.")
  }
}

function expandRecurring(
  definition: Extract<PdtpScheduleDefinition, { kind: "recurring" }>,
  range: { startDate: string; endDate: string },
): PdtpScheduledOccurrence[] {
  const programRange = clampRange(range)
  const definitionStart = toUtcDate(parseCivilDate(definition.startDate))
  const definitionEnd = toUtcDate(parseCivilDate(definition.endDate))
  if (definitionStart > definitionEnd) throw new Error("La recurrencia tiene un rango inválido.")
  const start = definitionStart > programRange.start ? definitionStart : programRange.start
  const end = definitionEnd < programRange.end ? definitionEnd : programRange.end
  if (start > end) return []
  const every = Math.max(1, Math.trunc(definition.every))
  const quantity = Math.max(0, Number(definition.plannedQuantity ?? 1))
  const results: PdtpScheduledOccurrence[] = []

  if (definition.unit === "day") {
    const anchor = definitionStart
    for (let cursor = start; cursor <= end; cursor = addDays(cursor, 1)) {
      const offset = Math.floor((cursor.getTime() - anchor.getTime()) / 86_400_000)
      if (offset >= 0 && offset % every === 0) results.push(occurrence(toCivilDate(cursor), quantity))
    }
    return results
  }

  if (definition.unit === "week") {
    const weekdays = [...new Set((definition.weekdays?.length ? definition.weekdays : [definitionStart.getUTCDay() === 0 ? 7 : definitionStart.getUTCDay()]))]
      .filter((weekday) => weekday >= 1 && weekday <= 7)
      .sort((a, b) => a - b)
    const anchorWeek = startOfIsoWeek(definitionStart)
    for (let cursor = start; cursor <= end; cursor = addDays(cursor, 1)) {
      const weekday = cursor.getUTCDay() === 0 ? 7 : cursor.getUTCDay()
      const offsetWeeks = Math.floor((startOfIsoWeek(cursor).getTime() - anchorWeek.getTime()) / (7 * 86_400_000))
      if (offsetWeeks >= 0 && offsetWeeks % every === 0 && weekdays.includes(weekday)) results.push(occurrence(toCivilDate(cursor), quantity))
    }
    return results
  }

  const anchorDay = definition.dayOfMonth ?? definitionStart.getUTCDate()
  let cursor = definition.unit === "month" ? addMonthsClamped(definitionStart, 0, anchorDay) : addYearsClamped(definitionStart, 0, anchorDay)
  while (cursor < start) {
    cursor = definition.unit === "month"
      ? addMonthsClamped(cursor, every, anchorDay)
      : addYearsClamped(cursor, every, anchorDay)
  }
  while (cursor <= end) {
    if (cursor >= start) results.push(occurrence(toCivilDate(cursor), quantity))
    cursor = definition.unit === "month"
      ? addMonthsClamped(cursor, every, anchorDay)
      : addYearsClamped(cursor, every, anchorDay)
  }
  return results
}

/** Expands only calendar-backed definitions. Event/on-demand definitions are obligations. */
export function expandPdtpScheduleDefinition(
  definition: PdtpScheduleDefinition,
  programPeriod: { startDate: string; endDate: string },
): PdtpScheduledOccurrence[] {
  if (definition.kind === "one_time") {
    const range = clampRange(programPeriod)
    const date = toUtcDate(parseCivilDate(definition.date))
    return date >= range.start && date <= range.end ? [occurrence(definition.date, 1)] : []
  }
  if (definition.kind === "recurring") return expandRecurring(definition, programPeriod)
  return []
}

export type PdtpScheduleRemapNote = {
  kind:
    /** El rango cubría todo el período de origen y pasa a cubrir todo el año destino. */
    | "full_year"
    /** Rango parcial (p. ej. desde la activación o una v+1): se re-ancla fecha a fecha. */
    | "partial_range"
    /** Semanal sin días explícitos: se fija el día de la semana de origen. */
    | "weekdays_fixed"
    /** Cada N (>1) días o semanas: el ritmo continúa desde el inicio del año destino. */
    | "phase_may_shift"
    /** Un 29 de febrero pasó al 28 porque el año destino no es bisiesto. */
    | "leap_day_moved"
  message: string
}

function isoWeekday(date: string): number {
  const day = toUtcDate(parseCivilDate(date)).getUTCDay()
  return day === 0 ? 7 : day
}

function remapCivilDate(value: string, targetYear: number): { date: string; leapDayMoved: boolean } {
  const { month, day } = parseCivilDate(value)
  const lastDay = daysInMonth(targetYear, month)
  const clamped = Math.min(day, lastDay)
  return {
    date: `${String(targetYear).padStart(4, "0")}-${String(month).padStart(2, "0")}-${String(clamped).padStart(2, "0")}`,
    leapDayMoved: clamped !== day,
  }
}

/**
 * PREV-C03.1: traslada una programación fechada al año siguiente para la copia
 * anual del programa.
 *
 * Re-anclar fecha a fecha no basta, y la diferencia se nota en el calendario:
 * - una semanal sin `weekdays` usa el día de la semana de su `startDate`, y el
 *   mismo día del año siguiente cae otro día de la semana (2026-01-05 es lunes,
 *   2027-01-05 martes). Se fijan los días explícitos con la fecha de origen;
 * - un rango que cubría el año completo pasa a cubrir el año destino completo,
 *   en vez de arrastrar un borde que ya no corresponde;
 * - un rango parcial (desde la activación o desde una v+1 a mitad de año) se
 *   re-ancla literalmente y queda anotado, porque quizá haya que ampliarlo.
 *
 * Devuelve las notas para el informe de copia.
 */
export function remapPdtpScheduleDefinitionToYear(
  definition: PdtpScheduleDefinition | null | undefined,
  input: { sourcePeriod: { startDate: string; endDate: string }; targetYear: number },
): { definition: PdtpScheduleDefinition | null; notes: PdtpScheduleRemapNote[] } {
  if (!definition) return { definition: definition ?? null, notes: [] }
  const notes: PdtpScheduleRemapNote[] = []

  if (definition.kind === "one_time") {
    const { date, leapDayMoved } = remapCivilDate(definition.date, input.targetYear)
    if (leapDayMoved) notes.push({ kind: "leap_day_moved", message: `La fecha ${definition.date} pasó al ${date}: ${input.targetYear} no es bisiesto.` })
    return { definition: { ...definition, date }, notes }
  }
  if (definition.kind !== "recurring") return { definition, notes }

  const next: Extract<PdtpScheduleDefinition, { kind: "recurring" }> = { ...definition }
  if (definition.unit === "week" && !definition.weekdays?.length) {
    next.weekdays = [isoWeekday(definition.startDate)]
    notes.push({ kind: "weekdays_fixed", message: "Semanal sin días declarados: se conserva el día de la semana de origen." })
  }
  const coversFullSourcePeriod = definition.startDate === input.sourcePeriod.startDate && definition.endDate === input.sourcePeriod.endDate
  if (coversFullSourcePeriod) {
    next.startDate = `${input.targetYear}-01-01`
    next.endDate = `${input.targetYear}-12-31`
    notes.push({ kind: "full_year", message: `Cubre el año completo ${input.targetYear}.` })
  } else {
    const start = remapCivilDate(definition.startDate, input.targetYear)
    const end = remapCivilDate(definition.endDate, input.targetYear)
    next.startDate = start.date
    next.endDate = end.date
    notes.push({ kind: "partial_range", message: `Rango parcial re-anclado: ${start.date} a ${end.date}. Revisa si debe cubrir el año completo.` })
    if (start.leapDayMoved || end.leapDayMoved) notes.push({ kind: "leap_day_moved", message: `Un 29 de febrero pasó al 28: ${input.targetYear} no es bisiesto.` })
  }
  if ((definition.unit === "day" || definition.unit === "week") && Math.trunc(definition.every) > 1) {
    notes.push({ kind: "phase_may_shift", message: `Cada ${Math.trunc(definition.every)} ${definition.unit === "day" ? "días" : "semanas"}: el ritmo parte de nuevo desde el inicio del rango en ${input.targetYear}.` })
  }
  return { definition: next, notes }
}
