/**
 * Authoring model for dates generated by a Preventive Program activity.
 *
 * This module deliberately works with civil ISO dates rather than `Date` at
 * the API boundary.  A schedule is a calendar contract, not an instant, so a
 * browser/server timezone must not move an occurrence to the previous day.
 */

export type PdtpScheduleDefinition =
  | { version: 1; kind: "one_time"; date: string }
  | {
      version: 1
      kind: "recurring"
      startDate: string
      endDate: string
      every: number
      unit: "day" | "week" | "month" | "year"
      weekdays?: number[]
      dayOfMonth?: number
      plannedQuantity?: number
    }
  | {
      version: 1
      kind: "event"
      triggerConnectorKey: string
      triggerEventKey: string
      dueValue: number
      dueUnit: "hour" | "day"
    }
  | { version: 1; kind: "on_demand"; dueValue: number; dueUnit: "hour" | "day" }
  | { version: 1; kind: "legacy_grid" }

export type PdtpIsoWeek = { isoWeekYear: number; isoWeek: number }

export type PdtpScheduledOccurrence = PdtpIsoWeek & {
  scheduledFor: string
  plannedQuantity: number
}

/**
 * Human-readable SLA used by the planning and obligation views.  Event and
 * on-demand activities may use either civil days or elapsed hours; keeping the
 * formatting next to the schedule contract avoids rendering an hour-based
 * activity as `null día(s)` in one of the legacy views.
 */
export function describePdtpDue(
  dueDays: number | null | undefined,
  dueHours: number | null | undefined,
): string | null {
  if (dueHours !== null && dueHours !== undefined) return `${dueHours} hora(s)`
  if (dueDays !== null && dueDays !== undefined) return `${dueDays} día(s)`
  return null
}

type CivilDateParts = { year: number; month: number; day: number }

const ISO_DATE_RE = /^(\d{4})-(\d{2})-(\d{2})$/

function parseCivilDate(value: string): CivilDateParts {
  const match = ISO_DATE_RE.exec(value)
  if (!match) throw new Error(`Fecha civil inválida: ${value}`)
  const year = Number(match[1])
  const month = Number(match[2])
  const day = Number(match[3])
  const candidate = new Date(Date.UTC(year, month - 1, day))
  if (candidate.getUTCFullYear() !== year || candidate.getUTCMonth() + 1 !== month || candidate.getUTCDate() !== day) {
    throw new Error(`Fecha civil inválida: ${value}`)
  }
  return { year, month, day }
}

function toUtcDate(parts: CivilDateParts): Date {
  return new Date(Date.UTC(parts.year, parts.month - 1, parts.day))
}

function toCivilDate(date: Date): string {
  return date.toISOString().slice(0, 10)
}

function daysInMonth(year: number, month: number): number {
  return new Date(Date.UTC(year, month, 0)).getUTCDate()
}

function addDays(date: Date, days: number): Date {
  const result = new Date(date)
  result.setUTCDate(result.getUTCDate() + days)
  return result
}

function addMonthsClamped(date: Date, months: number, dayOfMonth?: number): Date {
  const target = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + months, 1))
  const desiredDay = dayOfMonth ?? date.getUTCDate()
  target.setUTCDate(Math.min(Math.max(1, desiredDay), daysInMonth(target.getUTCFullYear(), target.getUTCMonth() + 1)))
  return target
}

function addYearsClamped(date: Date, years: number, dayOfMonth?: number): Date {
  return addMonthsClamped(date, years * 12, dayOfMonth)
}

function startOfIsoWeek(date: Date): Date {
  const weekday = date.getUTCDay() === 0 ? 7 : date.getUTCDay()
  return addDays(date, 1 - weekday)
}

/** Returns ISO-8601 week-year and week (Monday is day 1). */
export function getPdtpIsoWeek(value: string | Date): PdtpIsoWeek {
  const date = typeof value === "string" ? toUtcDate(parseCivilDate(value)) : new Date(value)
  const thursday = addDays(date, 4 - (date.getUTCDay() === 0 ? 7 : date.getUTCDay()))
  const isoWeekYear = thursday.getUTCFullYear()
  const firstThursday = new Date(Date.UTC(isoWeekYear, 0, 4))
  const diffDays = Math.floor((startOfIsoWeek(thursday).getTime() - startOfIsoWeek(firstThursday).getTime()) / 86_400_000)
  return { isoWeekYear, isoWeek: Math.floor(diffDays / 7) + 1 }
}

/** Lists the ISO weeks touched by any civil day of a calendar month. */
export function listPdtpIsoWeeksIntersectingMonth(year: number, month: number): PdtpIsoWeek[] {
  if (!Number.isInteger(year) || !Number.isInteger(month) || month < 1 || month > 12) throw new Error("Mes inválido.")
  const seen = new Set<string>()
  const result: PdtpIsoWeek[] = []
  const first = new Date(Date.UTC(year, month - 1, 1))
  const last = new Date(Date.UTC(year, month, 0))
  for (let cursor = first; cursor <= last; cursor = addDays(cursor, 1)) {
    const week = getPdtpIsoWeek(cursor)
    const key = `${week.isoWeekYear}-${week.isoWeek}`
    if (!seen.has(key)) {
      seen.add(key)
      result.push(week)
    }
  }
  return result
}

function occurrence(scheduledFor: string, plannedQuantity: number): PdtpScheduledOccurrence {
  return { scheduledFor, ...getPdtpIsoWeek(scheduledFor), plannedQuantity }
}

function clampRange(range: { startDate: string; endDate: string }): { start: Date; end: Date } {
  const start = toUtcDate(parseCivilDate(range.startDate))
  const end = toUtcDate(parseCivilDate(range.endDate))
  if (start > end) throw new Error("El período de programación es inválido.")
  return { start, end }
}

/**
 * Definiciones calendarizadas nuevas no pueden quedar parcialmente fuera del
 * período anual. La expansión sigue recibiendo un rango para leer datos
 * históricos y hacer el clamp defensivo, pero la escritura debe rechazar una
 * configuración que dejaría al usuario creyendo que programó una ocurrencia
 * que luego nunca se materializaría.
 */
export function assertPdtpScheduleDefinitionWithinPeriod(
  definition: PdtpScheduleDefinition | null | undefined,
  period: { startDate: string; endDate: string },
): void {
  if (!definition || definition.kind === "event" || definition.kind === "on_demand" || definition.kind === "legacy_grid") return
  const range = clampRange(period)
  if (definition.kind === "one_time") {
    const date = toUtcDate(parseCivilDate(definition.date))
    if (date < range.start || date > range.end) {
      throw new Error("La fecha planificada debe estar dentro del período del programa.")
    }
    return
  }

  const start = toUtcDate(parseCivilDate(definition.startDate))
  const end = toUtcDate(parseCivilDate(definition.endDate))
  if (start < range.start || end > range.end) {
    throw new Error("El rango de recurrencia debe estar dentro del período del programa.")
  }
}

function expandRecurring(
  definition: Extract<PdtpScheduleDefinition, { kind: "recurring" }>,
  range: { startDate: string; endDate: string },
): PdtpScheduledOccurrence[] {
  const programRange = clampRange(range)
  const definitionStart = toUtcDate(parseCivilDate(definition.startDate))
  const definitionEnd = toUtcDate(parseCivilDate(definition.endDate))
  if (definitionStart > definitionEnd) throw new Error("La recurrencia tiene un rango inválido.")
  const start = definitionStart > programRange.start ? definitionStart : programRange.start
  const end = definitionEnd < programRange.end ? definitionEnd : programRange.end
  if (start > end) return []
  const every = Math.max(1, Math.trunc(definition.every))
  const quantity = Math.max(0, Number(definition.plannedQuantity ?? 1))
  const results: PdtpScheduledOccurrence[] = []

  if (definition.unit === "day") {
    const anchor = definitionStart
    for (let cursor = start; cursor <= end; cursor = addDays(cursor, 1)) {
      const offset = Math.floor((cursor.getTime() - anchor.getTime()) / 86_400_000)
      if (offset >= 0 && offset % every === 0) results.push(occurrence(toCivilDate(cursor), quantity))
    }
    return results
  }

  if (definition.unit === "week") {
    const weekdays = [...new Set((definition.weekdays?.length ? definition.weekdays : [definitionStart.getUTCDay() === 0 ? 7 : definitionStart.getUTCDay()]))]
      .filter((weekday) => weekday >= 1 && weekday <= 7)
      .sort((a, b) => a - b)
    const anchorWeek = startOfIsoWeek(definitionStart)
    for (let cursor = start; cursor <= end; cursor = addDays(cursor, 1)) {
      const weekday = cursor.getUTCDay() === 0 ? 7 : cursor.getUTCDay()
      const offsetWeeks = Math.floor((startOfIsoWeek(cursor).getTime() - anchorWeek.getTime()) / (7 * 86_400_000))
      if (offsetWeeks >= 0 && offsetWeeks % every === 0 && weekdays.includes(weekday)) results.push(occurrence(toCivilDate(cursor), quantity))
    }
    return results
  }

  const anchorDay = definition.dayOfMonth ?? definitionStart.getUTCDate()
  let cursor = definition.unit === "month" ? addMonthsClamped(definitionStart, 0, anchorDay) : addYearsClamped(definitionStart, 0, anchorDay)
  while (cursor < start) {
    cursor = definition.unit === "month"
      ? addMonthsClamped(cursor, every, anchorDay)
      : addYearsClamped(cursor, every, anchorDay)
  }
  while (cursor <= end) {
    if (cursor >= start) results.push(occurrence(toCivilDate(cursor), quantity))
    cursor = definition.unit === "month"
      ? addMonthsClamped(cursor, every, anchorDay)
      : addYearsClamped(cursor, every, anchorDay)
  }
  return results
}

/** Expands only calendar-backed definitions. Event/on-demand definitions are obligations. */
export function expandPdtpScheduleDefinition(
  definition: PdtpScheduleDefinition,
  programPeriod: { startDate: string; endDate: string },
): PdtpScheduledOccurrence[] {
  if (definition.kind === "one_time") {
    const range = clampRange(programPeriod)
    const date = toUtcDate(parseCivilDate(definition.date))
    return date >= range.start && date <= range.end ? [occurrence(definition.date, 1)] : []
  }
  if (definition.kind === "recurring") return expandRecurring(definition, programPeriod)
  return []
}
