/**
 * Archivos de test que usan @electric-sql/pglite (Postgres WASM in-memory).
 *
 * Cada uno instancia su propia BD y ejecuta migraciones completas, lo que
 * satura CPU si se ejecutan en paralelo. Se asignan a un proyecto vitest
 * separado con fileParallelism: false.
 *
 * ⚠️  Al agregar un nuevo test PGlite: agrégalo aquí para que se excluya
 *     del proyecto paralelo y se ejecute secuencialmente.
 */
export const pgliteTestFiles = [
  "db/schema-consistency.test.ts",
  "db/__tests__/operational-integrity-constraints.test.ts",
  "db/__tests__/pdtp-worksite-cascade.test.ts",
  "db/__tests__/pdtp-check-constraints.test.ts",
  "db/__tests__/pdtp-catalog-activity-constraints.test.ts",
  "db/__tests__/purchase-credit-note-constraints.test.ts",
  // COM-002: el CHECK que impide declarar un medidor reemplazado sin motivo.
  "db/__tests__/fuel-load-meter-replacement-constraints.test.ts",
  "db/__tests__/container-subject-constraints.test.ts",
  "lib/services/billing/__tests__/sync-integration.test.ts",
  "lib/services/billing/__tests__/queries-scope.test.ts",
  "lib/services/billing/__tests__/payments-integration.test.ts",
  "lib/services/billing/__tests__/duplicates-integration.test.ts",
  "lib/__tests__/admin-user-scope.test.ts",
  "lib/__tests__/admin-roles-service.test.ts",
  "lib/__tests__/bootstrap.test.ts",
  "lib/__tests__/cancel-request-service.test.ts",
  "lib/__tests__/create-submitted-request-service.test.ts",
  "lib/__tests__/invoice-reconciliation-service.test.ts",
  "lib/__tests__/invoice-line-allocations-service.test.ts",
  "lib/__tests__/operational-integrity-ledger.test.ts",
  "lib/__tests__/pago-manual-idempotente.test.ts",
  "lib/__tests__/analytics-chile-day.test.ts",
  "lib/__tests__/operational-integrity-watermark.test.ts",
  "scripts/verify-purchase-invoice-allocations.test.ts",
  // Los fixtures de `npm run ss` contra las migraciones reales: sin esto, una
  // migración podía invalidarlos y el repo no lo sabía hasta correr la
  // auditoría completa (caso 0281 / TIA-001, 2026-09-15).
  "scripts/capture-fixtures-pglite.test.ts",
  "lib/__tests__/preflight-invoice-reconciliation.test.ts",
  "lib/__tests__/epp-stock-availability.test.ts",
  "lib/__tests__/deliveries-size-stock-pglite.test.ts",
  "lib/__tests__/epp-delivery-scale-reconciliation.test.ts",
  "lib/__tests__/epp-import-family-type.test.ts",
  "lib/__tests__/epp-import-size-family.test.ts",
  "lib/__tests__/epp-clothing-sizes.test.ts",
  "lib/__tests__/size-catalog-sync.test.ts",
  "lib/__tests__/epp-sizes-constraints.test.ts",
  "lib/__tests__/epp-duplicate-size-reconciliation.test.ts",
  "lib/__tests__/request-status-reconciliation.test.ts",
  "lib/__tests__/admin-product-attributes-persistence.test.ts",
  "lib/__tests__/epp-family-form.test.ts",
  "lib/__tests__/product-units-catalog.test.ts",
  // CAT-003: la FK de unidad y el rechazo por fila del importador masivo.
  "lib/__tests__/cat-003-unidad-producto-catalogo.test.ts",
  "lib/__tests__/operational-work-queue-quotation-source.test.ts",
  // E2E-004: la cola operacional también vigila el pago de la factura.
  "lib/__tests__/e2e-004-cola-vigila-el-pago.test.ts",
  // PEND-003: la CTA de seguimiento SST abre su propia evaluación.
  "lib/__tests__/pend-003-cta-seguimiento-sst.test.ts",
  "lib/__tests__/operational-work-queue-capa-duplicada.test.ts",
  "lib/__tests__/operational-work-queue-row-identity.test.ts",
  "lib/__tests__/combustibles-scope.test.ts",
  "lib/__tests__/ti-dashboard-assets-by-age.test.ts",
  "lib/__tests__/compras-export-invoice-filter.test.ts",
  // Faltaba desde que se escribió: instancia PGlite y migra, así que corriendo
  // en el proyecto paralelo competía por CPU con los demás.
  "lib/__tests__/compras-inbox-scope.test.ts",
  // Faltaban desde que se escribieron: instancian PGlite y migran, así que
  // corriendo en el proyecto paralelo competían por CPU con los demás.
  "lib/__tests__/operational-work-queue-pdtp-activity-source.test.ts",
  "lib/__tests__/pdtp-accreditation.test.ts",
  "lib/__tests__/pdtp-catalog-activities.test.ts",
  "lib/__tests__/pdtp-accreditation-bindings.test.ts",
  "lib/__tests__/prevention-training-occurrences-migration.test.ts",
  "lib/__tests__/prevention-training-occurrences-pglite.test.ts",
  "lib/__tests__/worksite-deactivation-pdtp.test.ts",
  "lib/__tests__/code-sequences.test.ts",
  "lib/__tests__/dispatch-guides.test.ts",
  "lib/__tests__/gdi-002-entrega-stock-en-transito.test.ts",
  "lib/__tests__/e2e-001-recorte-saldo-avisa-solicitante.test.ts",
  // APR-002: la aprobación masiva avisa al solicitante igual que la individual.
  "lib/__tests__/apr-002-aprobacion-masiva-avisa-solicitante.test.ts",
  "lib/__tests__/document-chain.test.ts",
  "lib/__tests__/equipment-performance-integration.test.ts",
  "lib/__tests__/feedback.test.ts",
  "lib/__tests__/feedback-sla-reminders.test.ts",
  "lib/__tests__/accountable-fuel-loads.test.ts",
  "lib/__tests__/fleet-document-versioning.test.ts",
  "lib/__tests__/fuel-cycle-integration.test.ts",
  "lib/__tests__/copec-sync-state-pglite.test.ts",
  "lib/__tests__/fuel-provider-supplier-catalog.test.ts",
  "lib/__tests__/fuel-provider-reconciliation.test.ts",
  "lib/__tests__/fuel-load-lifecycle.test.ts",
  "lib/__tests__/fuel-cycle-invariants.test.ts",
  "lib/__tests__/fuel-load-anomaly-reevaluation.test.ts",
  // Faltaba desde que se escribió: instancia PGlite y migra, igual que las de
  // arriba con el mismo comentario.
  "lib/__tests__/anomaly-detection-integration.test.ts",
  "lib/__tests__/full-flow-integration.test.ts",
  "lib/__tests__/integration-rbac-sequences.test.ts",
  "lib/__tests__/item-state-mutations.test.ts",
  "lib/__tests__/module-toggles.test.ts",
  "lib/__tests__/tae-import-ledger-scope.test.ts",
  "lib/__tests__/notification-permission-targeting.test.ts",
  "lib/__tests__/notification-service.test.ts",
  "lib/__tests__/operational-assignments.test.ts",
  "lib/__tests__/pending-purchase-queue.test.ts",
  "lib/__tests__/pdtp-coverage-r2.test.ts",
  "lib/__tests__/pdtp-compliance-zero.test.ts",
  // Tarea 3.2: desvíos por celda aplicados en la costura única
  // (loadProgramScheduleAndExecutions) — indicador, RE-36, exclusión mutua
  // con ejecuciones y no-alteración de la huella firmada.
  "lib/__tests__/pdtp-deviations.test.ts",
  // Fase 5: asignación nominal de actividades a personas, por faena.
  "lib/__tests__/pdtp-assignees.test.ts",
  // Fase 4: el cierre mensual por faena y su distribución por correo.
  "lib/__tests__/pdtp-period-closures.test.ts",
  "lib/__tests__/pdtp-closure-distribution.test.ts",
  "lib/__tests__/pdtp-re36-document.test.ts",
  "lib/__tests__/pdtp-capability-subjects.test.ts",
  "lib/__tests__/pdtp-checklist-action-plan.test.ts",
  "lib/__tests__/pdtp-fulfillment.test.ts",
  "lib/__tests__/pdtp-lifecycle-instrument-gate.test.ts",
  "lib/__tests__/pdtp-constancias.test.ts",
  "lib/__tests__/prevention-alcotest.test.ts",
  "lib/__tests__/prevention-cgrd.test.ts",
  "lib/__tests__/pdtp-coverage-sources.test.ts",
  "lib/__tests__/pdtp-evidence-gc.test.ts",
  "lib/__tests__/risk-map-gc.test.ts",
  "lib/__tests__/pdtp-reminders-dedup.test.ts",
  "lib/__tests__/pdtp-revision-diff-decisions.test.ts",
  "lib/__tests__/pdtp-revocations.test.ts",
  "lib/__tests__/pdtp-objectives.test.ts",
  "scripts/__tests__/apply-pdtp-2026-objectives.test.ts",
  "lib/__tests__/pdtp-worksites.test.ts",
  "lib/__tests__/pdtp-schedule-presets-batch.test.ts",
  "lib/__tests__/physical-inventory-service.test.ts",
  "lib/__tests__/prevention-pdtp.test.ts",
  "lib/__tests__/prevention-capa-list.test.ts",
  "lib/__tests__/prevention-capa-manual-y-exencion.test.ts",
  "lib/__tests__/prevention-incident-public-reports.test.ts",
  "lib/__tests__/prevention-cphs-program-persistence.test.ts",
  "lib/__tests__/prevention-cphs-certification-persistence.test.ts",
  "lib/__tests__/prevention-hygiene-pdtp-accreditation.test.ts",
  "lib/__tests__/pdtp-competency-gap-obligation.test.ts",
  "lib/__tests__/pdtp-indicators-reopen-revocation.test.ts",
  "lib/__tests__/prevention-emergency-plan-seed.test.ts",
  // PER-001 y E2E-005 de la auditoría 2026-09-14.
  "lib/__tests__/prevention-permit-crew-ack-blocker.test.ts",
  "lib/__tests__/prevention-acuse-sin-cuenta.test.ts",
  "lib/__tests__/prevention-risk-control-ineffective-capa.test.ts",
  "lib/__tests__/pdtp-preventive-organization-obligation.test.ts",
  "lib/__tests__/pdtp-worker-lifecycle-obligation.test.ts",
  "lib/__tests__/pdtp-worker-onboarding-accreditation.test.ts",
  "lib/__tests__/pdtp-worker-sensitivity-accreditation.test.ts",
  "lib/__tests__/pdtp-epp-delivery-accreditation.test.ts",
  "lib/__tests__/worksite-lifecycle.test.ts",
  "lib/__tests__/prevention-emergency-list.test.ts",
  "lib/__tests__/emergency-resource-inventory-pglite.test.ts",
  "lib/__tests__/prevention-containers-pglite.test.ts",
  "lib/__tests__/prevention-inspection-container-subject-pglite.test.ts",
  // Faltaba desde que se escribió (Grupo B): instancia PGlite y migra, así que
  // en el proyecto paralelo competía por CPU y corría con el timeout de 20 s,
  // no con los 60 s que necesita la instrumentación de `--coverage` del CI.
  "lib/__tests__/prevention-dia-civil-chileno.test.ts",
  "lib/__tests__/prevention-documents-persistence.test.ts",
  "lib/__tests__/prevention-ppa-workflow-persistence.test.ts",
  "lib/__tests__/purchasing-service.test.ts",
  "lib/__tests__/service-items-flow.test.ts",
  "lib/__tests__/receiving-two-stage.test.ts",
  "lib/__tests__/registro-action.test.ts",
  "lib/__tests__/requests-delete.test.ts",
  "lib/__tests__/sst-alerts.test.ts",
  "lib/__tests__/sst-delete-evaluation.test.ts",
  "lib/__tests__/sst-integrity-constraints.test.ts",
  "lib/__tests__/stock-alerts.test.ts",
  "lib/__tests__/bodega-min-stock-bulk.test.ts",
  "lib/__tests__/stock-documents.test.ts",
  "lib/__tests__/stock-export.test.ts",
  "lib/__tests__/stock-availability-pglite.test.ts",
  "lib/__tests__/stock-service.test.ts",
  // MNT-002: el egreso del repuesto consumido en una OT se prueba contra
  // Postgres real porque lo que hay que demostrar es el saldo resultante.
  "lib/__tests__/maintenance-part-stock.test.ts",
  "lib/__tests__/worker-stock-delivery.test.ts",
  "lib/__tests__/worker-position-backfill-pglite.test.ts",
  "lib/__tests__/worker-positions-service.test.ts",
  "lib/__tests__/worker-offboarding.test.ts",
  "lib/__tests__/password-reset.test.ts",
  // PRI-002: ejercita la supresión de un caso reservado contra PGlite migrado.
  "lib/__tests__/prevention-privacy-reserved-redaction.test.ts",
  "lib/__tests__/admin-productos-identidad-y-baja.test.ts",
  "lib/__tests__/proveedores-actions.test.ts",
  "lib/__tests__/facturacion-clientes-identidad.test.ts",
  "lib/__tests__/cron-run-ledger.test.ts",
  "lib/__tests__/deadline-reminders.test.ts",
  "lib/reports/export-module/solicitudes.test.ts",
  "lib/__tests__/segregacion-dinero.test.ts",
  "lib/__tests__/inspection-finding-closure.test.ts",
  "lib/__tests__/supplier-document-crosscheck.test.ts",
  "lib/__tests__/dashboard-fleet-documents-kpi.test.ts",
  "lib/__tests__/diagnose-delivery-quantities.test.ts",
  "lib/__tests__/trabajadores-scope.test.ts",
  "lib/__tests__/trazabilidad-export-scope.test.ts",
  "lib/__tests__/trazabilidad-item.test.ts",
  "lib/__tests__/traceability-integrity-cases.test.ts",
  "lib/__tests__/sst-document-taxonomy-pglite.test.ts",
  // ── Módulo TI ─────────────────────────────────────────────────────────────
  "lib/__tests__/ti-assets-pglite.test.ts",
  "lib/__tests__/ti-asset-types-pglite.test.ts",
  "lib/__tests__/ti-assignments-pglite.test.ts",
  "lib/__tests__/ti-tickets-pglite.test.ts",
  "lib/__tests__/ti-licenses-access-pglite.test.ts",
  "lib/__tests__/ti-maintenance-retirement-pglite.test.ts",
  "lib/__tests__/ti-alerts-pglite.test.ts",
  "lib/__tests__/ti-attachments-pglite.test.ts",
]
