import type { ModuleManifest } from "@/modules/manifest-types"

export const preventionModule = {
  id: "prevention",

  permissions: [
    "prevention:pdtp:view",
    "prevention:pdtp:execute",
    "prevention:pdtp:program:manage",
    "prevention:pdtp:approve",
    "prevention:pdtp:sign_legal",
    "prevention:pdtp:checklist:manage",
    "prevention:pdtp:checklist:fill",
    "prevention:pdtp:action:manage",
    "prevention:pdtp:action:verify",
    "prevention:docs:view",
    "prevention:docs:manage",
    "prevention:docs:submit_review",
    "prevention:docs:review",
    "prevention:docs:approve",
    "prevention:docs:publish",
    "prevention:docs:distribute",
    "prevention:docs:ack",
    "prevention:docs:link",
    "prevention:docs:archive",
    "prevention:docs:manage_sensitive",
    "prevention:docs:manage_restricted",
    "prevention:indicadores:view",
    "prevention:indicadores:manage",
    "prevention:indicadores:close",
    "prevention:health:view_restrictions",
    "prevention:health:view_clinical",
    "prevention:health:manage_surveillance",
    "prevention:health:upload_clinical",
    "prevention:reserved_case:view",
    "prevention:reserved_case:investigate",
    "prevention:privacy:audit",
    "prevention:privacy:manage_requests",
    "prevention:privacy:export_subject",
    "prevention:capa:view",
    "prevention:capa:manage",
    "prevention:capa:complete",
    "prevention:capa:verify",
    "prevention:capa:close",
    "prevention:capa:override_segregation",
    "prevention:capa:reconcile",
    "prevention:incidents:report",
    "prevention:incidents:view",
    "prevention:incidents:triage",
    "prevention:incidents:investigate",
    "prevention:incidents:notify",
    "prevention:incidents:authorize_restart",
    "prevention:incidents:close",
    "prevention:incidents:view_sensitive",
    "prevention:incidents:export",
    "prevention:risk:view",
    "prevention:risk:edit",
    "prevention:risk:review",
    "prevention:risk:approve",
    "prevention:risk:publish",
    "prevention:legal:view",
    "prevention:legal:assess",
    "prevention:legal:approve_applicability",
    "prevention:legal:export",
    "prevention:training:view",
    "prevention:training:manage",
    "prevention:training:approve",
    "prevention:training:deliver",
    "prevention:training:ack",
    "prevention:training:convalidate",
    "prevention:training:revoke",
    "prevention:training:export",
    "prevention:contractors:view",
    "prevention:contractors:manage",
    "prevention:contractors:submit",
    "prevention:contractors:accredit",
    "prevention:contractors:authorize_access",
    "prevention:contractors:coordinate",
    "prevention:contractors:export",
    "prevention:permits:view",
    "prevention:permits:manage",
    "prevention:permits:request",
    "prevention:permits:verify",
    "prevention:permits:approve",
    "prevention:permits:activate",
    "prevention:permits:suspend",
    "prevention:permits:close",
    "prevention:permits:export",
    "prevention:inspections:view",
    "prevention:inspections:manage",
    "prevention:inspections:approve",
    "prevention:inspections:execute",
    "prevention:inspections:review",
    "prevention:inspections:export",
    "prevention:cphs:view",
    "prevention:cphs:manage",
    "prevention:governance:review",
    "prevention:hygiene:view",
    "prevention:hygiene:manage",
    "prevention:hygiene:measure",
  ] as const,

  permissionMeta: {
    "prevention:pdtp:view":       { id: "p-prev-pdtp-view",       description: "Ver Programa de Trabajo Preventivo SG-SST" },
    "prevention:pdtp:execute":    { id: "p-prev-pdtp-execute",    description: "Registrar ejecuciones y evidencias del Programa de Trabajo Preventivo en faenas autorizadas" },
    "prevention:pdtp:program:manage": { id: "p-prev-pdtp-program-manage", description: "Administrar catálogo, cronograma y metas por faena del Programa de Trabajo Preventivo" },
    "prevention:pdtp:approve":    { id: "p-prev-pdtp-approve",    description: "Aprobar el Programa de Trabajo Preventivo como jefatura de prevención" },
    "prevention:pdtp:sign_legal": { id: "p-prev-pdtp-sign-legal", description: "Firmar el Programa de Trabajo Preventivo como Gerencia Legal y Recursos Humanos" },
    "prevention:pdtp:checklist:manage": { id: "p-prev-pdtp-cl-manage", description: "Crear/editar plantillas de checklist del PDTP" },
    "prevention:pdtp:checklist:fill":   { id: "p-prev-pdtp-cl-fill",   description: "Llenar el checklist de verificación en una ejecución del PDTP" },
    "prevention:pdtp:action:manage":    { id: "p-prev-pdtp-act-manage", description: "Crear/editar acciones correctivas y su seguimiento en el PDTP" },
    "prevention:pdtp:action:verify":    { id: "p-prev-pdtp-act-verify", description: "Verificar el cierre de acciones correctivas del PDTP" },
    "prevention:docs:view":               { id: "p-prev-docs-v",    description: "Ver la documentación preventiva" },
    "prevention:docs:manage":             { id: "p-prev-docs-m",    description: "Subir archivos, crear carpetas y crear versiones de documentos" },
    "prevention:docs:submit_review":      { id: "p-prev-docs-submit", description: "Enviar versiones documentales a revisión" },
    "prevention:docs:review":             { id: "p-prev-docs-review", description: "Revisar u observar versiones documentales" },
    "prevention:docs:approve":            { id: "p-prev-docs-approve", description: "Aprobar versiones documentales revisadas" },
    "prevention:docs:publish":            { id: "p-prev-docs-publish", description: "Publicar versiones documentales aprobadas" },
    "prevention:docs:distribute":         { id: "p-prev-docs-distribute", description: "Asignar destinatarios y exenciones para documentos" },
    "prevention:docs:ack":                { id: "p-prev-docs-ack", description: "Acusar recibo de una versión documental asignada" },
    "prevention:docs:link":               { id: "p-prev-docs-link", description: "Vincular documentos con entidades operacionales" },
    "prevention:docs:archive":            { id: "p-prev-docs-arch", description: "Archivar (soft delete) documentos" },
    "prevention:docs:manage_sensitive":   { id: "p-prev-docs-sens", description: "Gestionar documentos con confidencialidad 'sensible'" },
    "prevention:docs:manage_restricted":  { id: "p-prev-docs-rest", description: "Gestionar documentos con confidencialidad 'restringido'" },
    "prevention:indicadores:view":   { id: "p-prev-ind-view",   description: "Ver indicadores de accidentabilidad" },
    "prevention:indicadores:manage": { id: "p-prev-ind-manage", description: "Registrar/editar indicadores de accidentabilidad" },
    "prevention:indicadores:close":  { id: "p-prev-ind-close", description: "Cerrar períodos y corregir indicadores cerrados" },
    "prevention:health:view_restrictions": { id: "p-prev-health-restr", description: "Ver únicamente aptitud y restricciones ocupacionales necesarias" },
    "prevention:health:view_clinical": { id: "p-prev-health-clin", description: "Acceder a antecedentes clínicos cifrados por propósito autorizado" },
    "prevention:health:manage_surveillance": { id: "p-prev-health-surv", description: "Administrar programas de vigilancia ocupacional" },
    "prevention:health:upload_clinical": { id: "p-prev-health-upload", description: "Crear expedientes clínicos ocupacionales cifrados" },
    "prevention:reserved_case:view": { id: "p-prev-reserved-view", description: "Ver casos reservados en los que el usuario es miembro autorizado" },
    "prevention:reserved_case:investigate": { id: "p-prev-reserved-invest", description: "Investigar casos reservados asignados" },
    "prevention:privacy:audit": { id: "p-prev-privacy-audit", description: "Auditar accesos a dominios sensibles sin ver contenido clínico" },
    "prevention:privacy:manage_requests": { id: "p-prev-privacy-manage", description: "Gestionar solicitudes de derechos y retenciones de privacidad" },
    "prevention:privacy:export_subject": { id: "p-prev-privacy-export", description: "Preparar exportaciones minimizadas para derechos del titular" },
    "prevention:capa:view": { id: "p-prev-capa-view", description: "Ver acciones correctivas y preventivas dentro de la faena autorizada" },
    "prevention:capa:manage": { id: "p-prev-capa-manage", description: "Crear, asignar y actualizar acciones CAPA" },
    "prevention:capa:complete": { id: "p-prev-capa-complete", description: "Declarar implementación y enviar acciones CAPA a verificación" },
    "prevention:capa:verify": { id: "p-prev-capa-verify", description: "Verificar evidencia y eficacia de acciones CAPA" },
    "prevention:capa:close": { id: "p-prev-capa-close", description: "Cerrar acciones CAPA verificadas" },
    "prevention:capa:override_segregation": { id: "p-prev-capa-override", description: "Autorizar excepción fundamentada a la segregación de verificación CAPA" },
    "prevention:capa:reconcile": { id: "p-prev-capa-reconcile", description: "Conciliar acciones históricas migradas a CAPA" },
    "prevention:incidents:report": { id: "p-prev-inc-report", description: "Reportar incidentes en faenas autorizadas, incluida sincronización offline" },
    "prevention:incidents:view": { id: "p-prev-inc-view", description: "Ver la proyección operacional no sensible de incidentes" },
    "prevention:incidents:triage": { id: "p-prev-inc-triage", description: "Clasificar incidentes, medidas y responsables de notificación" },
    "prevention:incidents:investigate": { id: "p-prev-inc-invest", description: "Investigar incidentes y vincular evidencia y CAPA" },
    "prevention:incidents:notify": { id: "p-prev-inc-notify", description: "Registrar DIAT, DIEP y notificaciones fatal/grave con evidencia" },
    "prevention:incidents:authorize_restart": { id: "p-prev-inc-restart", description: "Autorizar de forma segregada el reinicio de una operación suspendida" },
    "prevention:incidents:close": { id: "p-prev-inc-close", description: "Aprobar lotes históricos y cerrar incidentes que cumplan todos los gates" },
    "prevention:incidents:view_sensitive": { id: "p-prev-inc-sensitive", description: "Acceder nominativamente a identidad, lesión y evidencia sensible de incidentes por propósito" },
    "prevention:incidents:export": { id: "p-prev-inc-export", description: "Exportar registro y expediente XLSX de incidentes dentro del alcance" },
    "prevention:risk:view": { id: "p-prev-risk-view", description: "Ver MIPER, controles críticos, revisiones y cobertura dentro de la faena autorizada" },
    "prevention:risk:edit": { id: "p-prev-risk-edit", description: "Crear versiones MIPER, importar peligros y gestionar disparadores de revisión" },
    "prevention:risk:review": { id: "p-prev-risk-review", description: "Revisar técnicamente versiones MIPER de forma segregada" },
    "prevention:risk:approve": { id: "p-prev-risk-approve", description: "Aprobar versiones y lotes MIPER de forma segregada" },
    "prevention:risk:publish": { id: "p-prev-risk-publish", description: "Publicar una versión MIPER inmutable y activar el reloj PDTP" },
    "prevention:legal:view": { id: "p-prev-legal-view", description: "Ver el registro legal y la aplicabilidad dentro de la faena autorizada" },
    "prevention:legal:assess": { id: "p-prev-legal-assess", description: "Preparar requisitos, proponer aplicabilidad y evaluar cumplimiento" },
    "prevention:legal:approve_applicability": { id: "p-prev-legal-approve", description: "Aprobar requisitos y aplicabilidad legal de forma segregada" },
    "prevention:legal:export": { id: "p-prev-legal-export", description: "Exportar registro legal, aplicabilidad, evidencia y brechas en XLSX" },
    "prevention:training:view": { id: "p-prev-train-view", description: "Ver cursos, sesiones, competencias y brechas dentro de la faena autorizada" },
    "prevention:training:manage": { id: "p-prev-train-manage", description: "Administrar catálogo, contenidos, sesiones y requisitos de competencia" },
    "prevention:training:approve": { id: "p-prev-train-approve", description: "Aprobar y publicar contenidos formativos de forma segregada del autor" },
    "prevention:training:deliver": { id: "p-prev-train-deliver", description: "Registrar asistencia, evaluación y cierre de una sesión de capacitación" },
    "prevention:training:ack": { id: "p-prev-train-ack", description: "Acusar recibo de la propia capacitación u ODI" },
    "prevention:training:convalidate": { id: "p-prev-train-conval", description: "Convalidar competencias externas con justificación y evidencia" },
    "prevention:training:revoke": { id: "p-prev-train-revoke", description: "Revocar una competencia vigente con motivo auditado" },
    "prevention:training:export": { id: "p-prev-train-export", description: "Exportar matriz de competencias, brechas y expediente formativo en XLSX" },
    "prevention:contractors:view": { id: "p-prev-contr-view", description: "Ver empresas contratistas, contratos, acreditación y coordinación de la faena autorizada" },
    "prevention:contractors:manage": { id: "p-prev-contr-manage", description: "Registrar empresas, contratos, personas y requisitos de acreditación" },
    "prevention:contractors:submit": { id: "p-prev-contr-submit", description: "Presentar evidencia documental de acreditación" },
    "prevention:contractors:accredit": { id: "p-prev-contr-accredit", description: "Aprobar u observar evidencia de acreditación de forma segregada de quien la presenta" },
    "prevention:contractors:authorize_access": { id: "p-prev-contr-access", description: "Liberar o bloquear el ingreso de un contratista a la faena según su acreditación" },
    "prevention:contractors:coordinate": { id: "p-prev-contr-coord", description: "Convocar y cerrar reuniones de coordinación DS 76 con acuerdos derivados a CAPA" },
    "prevention:contractors:export": { id: "p-prev-contr-export", description: "Exportar registro de faena, acreditación, brechas y coordinación en XLSX" },
    "prevention:permits:view": { id: "p-prev-permit-view", description: "Ver permisos de trabajo, AST y aislamientos de la faena autorizada" },
    "prevention:permits:manage": { id: "p-prev-permit-manage", description: "Administrar el catálogo de tipos de permiso de trabajo" },
    "prevention:permits:request": { id: "p-prev-permit-request", description: "Solicitar permisos de trabajo y elaborar su AST/JSA" },
    "prevention:permits:verify": { id: "p-prev-permit-verify", description: "Verificar controles, aplicar aislamientos LOTO y registrar mediciones" },
    "prevention:permits:approve": { id: "p-prev-permit-approve", description: "Aprobar, rechazar o extender un permiso de forma segregada del solicitante" },
    "prevention:permits:activate": { id: "p-prev-permit-activate", description: "Habilitar el inicio del trabajo una vez cumplidos todos los controles" },
    "prevention:permits:suspend": { id: "p-prev-permit-suspend", description: "Suspender un permiso vigente ante desviación o riesgo" },
    "prevention:permits:close": { id: "p-prev-permit-close", description: "Cerrar un permiso con todos los aislamientos retirados" },
    "prevention:permits:export": { id: "p-prev-permit-export", description: "Exportar permisos, AST, aislamientos y mediciones en XLSX" },
    "prevention:inspections:view": { id: "p-prev-insp-view", description: "Ver plantillas, programación, inspecciones y hallazgos de la faena autorizada" },
    "prevention:inspections:manage": { id: "p-prev-insp-manage", description: "Incorporar plantillas y programar inspecciones por faena y frecuencia" },
    "prevention:inspections:approve": { id: "p-prev-insp-approve", description: "Aprobar plantillas de inspección de forma segregada de quien las incorpora" },
    "prevention:inspections:execute": { id: "p-prev-insp-execute", description: "Ejecutar inspecciones en terreno, responder ítems y derivar hallazgos a CAPA" },
    "prevention:inspections:review": { id: "p-prev-insp-review", description: "Revisar y cerrar una inspección de forma independiente de quien la ejecutó" },
    "prevention:inspections:export": { id: "p-prev-insp-export", description: "Exportar inspecciones, respuestas, hallazgos y tendencias en XLSX" },
    "prevention:cphs:view": { id: "p-prev-cphs-view", description: "Ver comités paritarios, integrantes, sesiones y acuerdos de la faena autorizada" },
    "prevention:cphs:manage": { id: "p-prev-cphs-manage", description: "Constituir comités, designar integrantes, convocar sesiones y cerrar actas" },
    "prevention:governance:review": { id: "p-prev-gov-review", description: "Registrar y cerrar la revisión por la dirección del SG-SST" },
    "prevention:hygiene:view": { id: "p-prev-hyg-view", description: "Ver agentes, grupos de exposición, mediciones y cobertura de vigilancia" },
    "prevention:hygiene:manage": { id: "p-prev-hyg-manage", description: "Administrar agentes, grupos de exposición y programas de vigilancia ocupacional" },
    "prevention:hygiene:measure": { id: "p-prev-hyg-measure", description: "Registrar mediciones de exposición contra el límite permisible" },
  },

  nav: [
    {
      areaId: "prevencion",
      items: [
        {
          label: "MIPER y controles",
          href: "/prevencion/miper",
          iconName: "ShieldWarning",
          permissions: ["prevention:risk:view"],
        },
        {
          label: "Requisitos legales",
          href: "/prevencion/requisitos-legales",
          iconName: "Scales",
          permissions: ["prevention:legal:view"],
        },
        {
          label: "Programa preventivo SG-SST",
          href: "/prevencion/pdtp",
          iconName: "ClipboardText",
          permissions: ["prevention:pdtp:view"],
          children: [
            {
              label: "Aprobaciones",
              href: "/prevencion/pdtp/aprobaciones",
              permissions: ["prevention:pdtp:approve"],
            },
            {
              label: "Acciones correctivas",
              href: "/prevencion/pdtp/acciones",
              permissions: ["prevention:pdtp:view"],
            },
            {
              label: "Cobertura MIPER y legal",
              href: "/prevencion/pdtp/cobertura",
              permissions: ["prevention:pdtp:view"],
            },
          ],
        },
        {
          label: "Acciones CAPA",
          href: "/prevencion/capa",
          iconName: "CheckSquare",
          permissions: ["prevention:capa:view"],
        },
        {
          label: "Incidentes y denuncias",
          href: "/prevencion/incidentes",
          iconName: "Siren",
          permissions: ["prevention:incidents:view", "prevention:incidents:report"],
          children: [
            {
              label: "Reportar incidente",
              href: "/prevencion/incidentes/reportar",
              permissions: ["prevention:incidents:report"],
            },
          ],
        },
        {
          label: "Capacitación y competencias",
          href: "/prevencion/capacitacion",
          iconName: "Certificate",
          permissions: ["prevention:training:view"],
          children: [
            {
              label: "Matriz de competencias",
              href: "/prevencion/capacitacion/competencias",
              permissions: ["prevention:training:view"],
            },
            {
              label: "Brechas de competencia",
              href: "/prevencion/capacitacion/brechas",
              permissions: ["prevention:training:view"],
            },
          ],
        },
        {
          label: "Empresas contratistas",
          href: "/prevencion/contratistas",
          iconName: "Buildings",
          permissions: ["prevention:contractors:view"],
          children: [
            {
              label: "Brechas de acreditación",
              href: "/prevencion/contratistas/brechas",
              permissions: ["prevention:contractors:view"],
            },
            {
              label: "Coordinación DS 76",
              href: "/prevencion/contratistas/coordinacion",
              permissions: ["prevention:contractors:view"],
            },
          ],
        },
        {
          label: "Permisos de trabajo",
          href: "/prevencion/permisos",
          iconName: "ShieldCheck",
          permissions: ["prevention:permits:view"],
        },
        {
          label: "Inspecciones y auditorías",
          href: "/prevencion/inspecciones",
          iconName: "MagnifyingGlass",
          permissions: ["prevention:inspections:view"],
        },
        {
          label: "CPHS y gobernanza",
          href: "/prevencion/cphs",
          iconName: "UsersThree",
          permissions: ["prevention:cphs:view"],
        },
        {
          label: "Higiene y vigilancia",
          href: "/prevencion/higiene",
          iconName: "Heartbeat",
          permissions: ["prevention:hygiene:view"],
        },
        {
          label: "Documentación",
          href: "/prevencion/documentacion",
          iconName: "FolderOpen",
          permissions: ["prevention:docs:view"],
        },
        {
          label: "Indicadores de accidentabilidad",
          href: "/prevencion/indicadores",
          iconName: "ChartLineUp",
          permissions: ["prevention:indicadores:view"],
        },
      ],
    },
  ],

  defaultGrants: [
    // PDTP
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:view" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:execute" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:program:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:approve" },
    { roleSlug: "jefa_chome",          permission: "prevention:pdtp:view" },
    { roleSlug: "jefa_chome",          permission: "prevention:pdtp:approve" },
    { roleSlug: "jefa_chome",          permission: "prevention:pdtp:sign_legal" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:execute" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:view" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:execute" },
    { roleSlug: "jefe_terreno",        permission: "prevention:pdtp:view" },
    { roleSlug: "jefe_terreno",        permission: "prevention:pdtp:execute" },
    { roleSlug: "cphs",                permission: "prevention:pdtp:view" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:view" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:execute" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:program:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:approve" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:sign_legal" },
    // PDTP — Checklist / Plan de acción / Seguimiento
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:checklist:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:action:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:action:verify" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:checklist:fill" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:action:manage" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:checklist:fill" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:action:manage" },
    { roleSlug: "jefe_terreno",        permission: "prevention:pdtp:action:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:checklist:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:action:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:action:verify" },
    // Documentación
    { roleSlug: "prevencionista",      permission: "prevention:docs:view" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:submit_review" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:review" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:distribute" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:ack" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:link" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:archive" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:manage_restricted" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:submit_review" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:ack" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:view" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:review" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:approve" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:publish" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:distribute" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:ack" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:manage_sensitive" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:manage_restricted" },
    { roleSlug: "jefe_terreno",        permission: "prevention:docs:view" },
    { roleSlug: "jefe_terreno",        permission: "prevention:docs:ack" },
    { roleSlug: "administrador",       permission: "prevention:docs:view" },
    { roleSlug: "administrador",       permission: "prevention:docs:manage" },
    { roleSlug: "administrador",       permission: "prevention:docs:submit_review" },
    { roleSlug: "administrador",       permission: "prevention:docs:review" },
    { roleSlug: "administrador",       permission: "prevention:docs:approve" },
    { roleSlug: "administrador",       permission: "prevention:docs:publish" },
    { roleSlug: "administrador",       permission: "prevention:docs:distribute" },
    { roleSlug: "administrador",       permission: "prevention:docs:ack" },
    { roleSlug: "administrador",       permission: "prevention:docs:link" },
    { roleSlug: "administrador",       permission: "prevention:docs:archive" },
    { roleSlug: "administrador",       permission: "prevention:docs:manage_sensitive" },
    { roleSlug: "administrador",       permission: "prevention:docs:manage_restricted" },
    // Indicadores de accidentabilidad
    { roleSlug: "prevencionista",      permission: "prevention:indicadores:view" },
    { roleSlug: "prevencionista",      permission: "prevention:indicadores:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:indicadores:close" },
    { roleSlug: "prevencionista_faena", permission: "prevention:indicadores:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:indicadores:manage" },
    { roleSlug: "admin_contrato",       permission: "prevention:indicadores:view" },
    { roleSlug: "admin_contrato",       permission: "prevention:indicadores:manage" },
    { roleSlug: "jefa_chome",          permission: "prevention:indicadores:view" },
    { roleSlug: "cphs",                permission: "prevention:indicadores:view" },
    { roleSlug: "administrador",       permission: "prevention:indicadores:view" },
    { roleSlug: "administrador",       permission: "prevention:indicadores:manage" },
    { roleSlug: "administrador",       permission: "prevention:indicadores:close" },
    // MIPER y registro legal
    { roleSlug: "prevencionista", permission: "prevention:risk:view" },
    { roleSlug: "prevencionista", permission: "prevention:risk:edit" },
    { roleSlug: "prevencionista", permission: "prevention:risk:review" },
    { roleSlug: "prevencionista_faena", permission: "prevention:risk:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:risk:edit" },
    { roleSlug: "jefa_chome", permission: "prevention:risk:view" },
    { roleSlug: "jefa_chome", permission: "prevention:risk:review" },
    { roleSlug: "jefa_chome", permission: "prevention:risk:approve" },
    { roleSlug: "jefa_chome", permission: "prevention:risk:publish" },
    { roleSlug: "cphs", permission: "prevention:risk:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:risk:view" },
    { roleSlug: "administrador", permission: "prevention:risk:view" },
    { roleSlug: "administrador", permission: "prevention:risk:edit" },
    { roleSlug: "administrador", permission: "prevention:risk:review" },
    { roleSlug: "administrador", permission: "prevention:risk:approve" },
    { roleSlug: "administrador", permission: "prevention:risk:publish" },
    { roleSlug: "prevencionista", permission: "prevention:legal:view" },
    { roleSlug: "prevencionista", permission: "prevention:legal:assess" },
    { roleSlug: "prevencionista", permission: "prevention:legal:export" },
    { roleSlug: "prevencionista_faena", permission: "prevention:legal:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:legal:assess" },
    { roleSlug: "jefa_chome", permission: "prevention:legal:view" },
    { roleSlug: "jefa_chome", permission: "prevention:legal:assess" },
    { roleSlug: "jefa_chome", permission: "prevention:legal:approve_applicability" },
    { roleSlug: "jefa_chome", permission: "prevention:legal:export" },
    { roleSlug: "cphs", permission: "prevention:legal:view" },
    { roleSlug: "administrador", permission: "prevention:legal:view" },
    { roleSlug: "administrador", permission: "prevention:legal:assess" },
    { roleSlug: "administrador", permission: "prevention:legal:approve_applicability" },
    { roleSlug: "administrador", permission: "prevention:legal:export" },
    // Privacidad: no se otorgan por defecto permisos clínicos, de vigilancia
    // o casos reservados. Esos requieren grants nominativos y propósito formal.
    { roleSlug: "jefa_chome",          permission: "prevention:health:view_restrictions" },
    { roleSlug: "administrador",       permission: "prevention:health:view_restrictions" },
    { roleSlug: "jefa_chome",          permission: "prevention:privacy:audit" },
    { roleSlug: "jefa_chome",          permission: "prevention:privacy:manage_requests" },
    { roleSlug: "administrador",       permission: "prevention:privacy:audit" },
    { roleSlug: "administrador",       permission: "prevention:privacy:manage_requests" },
    { roleSlug: "administrador",       permission: "prevention:privacy:export_subject" },
    // CAPA común. La segregación de acciones altas/críticas se valida
    // además por actor en el servicio, no sólo mediante RBAC.
    { roleSlug: "prevencionista_faena", permission: "prevention:capa:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:capa:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:capa:complete" },
    { roleSlug: "prevencionista",       permission: "prevention:capa:view" },
    { roleSlug: "prevencionista",       permission: "prevention:capa:manage" },
    { roleSlug: "prevencionista",       permission: "prevention:capa:complete" },
    { roleSlug: "prevencionista",       permission: "prevention:capa:verify" },
    { roleSlug: "jefa_chome",           permission: "prevention:capa:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:capa:manage" },
    { roleSlug: "jefa_chome",           permission: "prevention:capa:complete" },
    { roleSlug: "jefa_chome",           permission: "prevention:capa:verify" },
    { roleSlug: "jefa_chome",           permission: "prevention:capa:close" },
    { roleSlug: "administrador",        permission: "prevention:capa:view" },
    { roleSlug: "administrador",        permission: "prevention:capa:manage" },
    { roleSlug: "administrador",        permission: "prevention:capa:complete" },
    { roleSlug: "administrador",        permission: "prevention:capa:verify" },
    { roleSlug: "administrador",        permission: "prevention:capa:close" },
    { roleSlug: "administrador",        permission: "prevention:capa:override_segregation" },
    { roleSlug: "administrador",        permission: "prevention:capa:reconcile" },
    // Incidentes: la proyección operacional se concede por rol y faena. El
    // permiso view_sensitive no tiene grants por defecto: requiere nominación.
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:report" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:triage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:investigate" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:notify" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:export" },
    { roleSlug: "prevencionista",       permission: "prevention:incidents:report" },
    { roleSlug: "prevencionista",       permission: "prevention:incidents:view" },
    { roleSlug: "prevencionista",       permission: "prevention:incidents:triage" },
    { roleSlug: "prevencionista",       permission: "prevention:incidents:investigate" },
    { roleSlug: "prevencionista",       permission: "prevention:incidents:notify" },
    { roleSlug: "prevencionista",       permission: "prevention:incidents:export" },
    { roleSlug: "admin_contrato",       permission: "prevention:incidents:report" },
    { roleSlug: "admin_contrato",       permission: "prevention:incidents:view" },
    { roleSlug: "jefe_terreno",         permission: "prevention:incidents:report" },
    { roleSlug: "jefe_terreno",         permission: "prevention:incidents:view" },
    { roleSlug: "cphs",                 permission: "prevention:incidents:view" },
    { roleSlug: "cphs",                 permission: "prevention:incidents:investigate" },
    { roleSlug: "jefa_chome",           permission: "prevention:incidents:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:incidents:triage" },
    { roleSlug: "jefa_chome",           permission: "prevention:incidents:investigate" },
    { roleSlug: "jefa_chome",           permission: "prevention:incidents:notify" },
    { roleSlug: "jefa_chome",           permission: "prevention:incidents:authorize_restart" },
    { roleSlug: "jefa_chome",           permission: "prevention:incidents:close" },
    { roleSlug: "jefa_chome",           permission: "prevention:incidents:export" },
    { roleSlug: "administrador",        permission: "prevention:incidents:report" },
    { roleSlug: "administrador",        permission: "prevention:incidents:view" },
    { roleSlug: "administrador",        permission: "prevention:incidents:triage" },
    { roleSlug: "administrador",        permission: "prevention:incidents:investigate" },
    { roleSlug: "administrador",        permission: "prevention:incidents:notify" },
    { roleSlug: "administrador",        permission: "prevention:incidents:authorize_restart" },
    { roleSlug: "administrador",        permission: "prevention:incidents:close" },
    { roleSlug: "administrador",        permission: "prevention:incidents:export" },
    // Capacitación, ODI y competencias. `convalidate` y `revoke` alteran la
    // habilitación de una persona sin que exista sesión ni evaluación: se
    // conceden sólo a jefatura/administración, nunca a roles de terreno.
    { roleSlug: "prevencionista",       permission: "prevention:training:view" },
    { roleSlug: "prevencionista",       permission: "prevention:training:manage" },
    { roleSlug: "prevencionista",       permission: "prevention:training:deliver" },
    { roleSlug: "prevencionista",       permission: "prevention:training:ack" },
    { roleSlug: "prevencionista",       permission: "prevention:training:export" },
    { roleSlug: "prevencionista_faena", permission: "prevention:training:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:training:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:training:deliver" },
    { roleSlug: "prevencionista_faena", permission: "prevention:training:ack" },
    { roleSlug: "admin_contrato",       permission: "prevention:training:view" },
    { roleSlug: "admin_contrato",       permission: "prevention:training:ack" },
    { roleSlug: "jefe_terreno",         permission: "prevention:training:view" },
    { roleSlug: "jefe_terreno",         permission: "prevention:training:ack" },
    { roleSlug: "cphs",                 permission: "prevention:training:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:training:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:training:manage" },
    { roleSlug: "jefa_chome",           permission: "prevention:training:approve" },
    { roleSlug: "jefa_chome",           permission: "prevention:training:convalidate" },
    { roleSlug: "jefa_chome",           permission: "prevention:training:revoke" },
    { roleSlug: "jefa_chome",           permission: "prevention:training:ack" },
    { roleSlug: "jefa_chome",           permission: "prevention:training:export" },
    { roleSlug: "administrador",        permission: "prevention:training:view" },
    { roleSlug: "administrador",        permission: "prevention:training:manage" },
    { roleSlug: "administrador",        permission: "prevention:training:approve" },
    { roleSlug: "administrador",        permission: "prevention:training:deliver" },
    { roleSlug: "administrador",        permission: "prevention:training:ack" },
    { roleSlug: "administrador",        permission: "prevention:training:convalidate" },
    { roleSlug: "administrador",        permission: "prevention:training:revoke" },
    { roleSlug: "administrador",        permission: "prevention:training:export" },
    // Contratistas DS 76. `accredit` y `authorize_access` deciden quién entra a
    // la faena: se separan de `submit` (quien presenta la evidencia) y no se
    // conceden juntos a un mismo rol de terreno.
    { roleSlug: "prevencionista",       permission: "prevention:contractors:view" },
    { roleSlug: "prevencionista",       permission: "prevention:contractors:manage" },
    { roleSlug: "prevencionista",       permission: "prevention:contractors:submit" },
    { roleSlug: "prevencionista",       permission: "prevention:contractors:accredit" },
    { roleSlug: "prevencionista",       permission: "prevention:contractors:coordinate" },
    { roleSlug: "prevencionista",       permission: "prevention:contractors:export" },
    { roleSlug: "prevencionista_faena", permission: "prevention:contractors:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:contractors:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:contractors:submit" },
    { roleSlug: "prevencionista_faena", permission: "prevention:contractors:coordinate" },
    { roleSlug: "admin_contrato",       permission: "prevention:contractors:view" },
    { roleSlug: "admin_contrato",       permission: "prevention:contractors:manage" },
    { roleSlug: "admin_contrato",       permission: "prevention:contractors:submit" },
    { roleSlug: "jefe_terreno",         permission: "prevention:contractors:view" },
    { roleSlug: "cphs",                 permission: "prevention:contractors:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:contractors:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:contractors:manage" },
    { roleSlug: "jefa_chome",           permission: "prevention:contractors:accredit" },
    { roleSlug: "jefa_chome",           permission: "prevention:contractors:authorize_access" },
    { roleSlug: "jefa_chome",           permission: "prevention:contractors:coordinate" },
    { roleSlug: "jefa_chome",           permission: "prevention:contractors:export" },
    { roleSlug: "administrador",        permission: "prevention:contractors:view" },
    { roleSlug: "administrador",        permission: "prevention:contractors:manage" },
    { roleSlug: "administrador",        permission: "prevention:contractors:submit" },
    { roleSlug: "administrador",        permission: "prevention:contractors:accredit" },
    { roleSlug: "administrador",        permission: "prevention:contractors:authorize_access" },
    { roleSlug: "administrador",        permission: "prevention:contractors:coordinate" },
    { roleSlug: "administrador",        permission: "prevention:contractors:export" },
    // Permisos de trabajo. La cadena solicitar → verificar → aprobar →
    // habilitar se reparte entre roles distintos: el servicio además impide
    // que el solicitante apruebe su propio permiso.
    { roleSlug: "jefe_terreno",         permission: "prevention:permits:view" },
    { roleSlug: "jefe_terreno",         permission: "prevention:permits:request" },
    { roleSlug: "jefe_terreno",         permission: "prevention:permits:verify" },
    { roleSlug: "jefe_terreno",         permission: "prevention:permits:suspend" },
    { roleSlug: "admin_contrato",       permission: "prevention:permits:view" },
    { roleSlug: "admin_contrato",       permission: "prevention:permits:request" },
    { roleSlug: "admin_contrato",       permission: "prevention:permits:suspend" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:request" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:verify" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:approve" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:activate" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:suspend" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:close" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:view" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:manage" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:request" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:verify" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:approve" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:activate" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:suspend" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:close" },
    { roleSlug: "prevencionista",       permission: "prevention:permits:export" },
    { roleSlug: "cphs",                 permission: "prevention:permits:view" },
    { roleSlug: "cphs",                 permission: "prevention:permits:suspend" },
    { roleSlug: "jefa_chome",           permission: "prevention:permits:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:permits:manage" },
    { roleSlug: "jefa_chome",           permission: "prevention:permits:approve" },
    { roleSlug: "jefa_chome",           permission: "prevention:permits:suspend" },
    { roleSlug: "jefa_chome",           permission: "prevention:permits:close" },
    { roleSlug: "jefa_chome",           permission: "prevention:permits:export" },
    { roleSlug: "administrador",        permission: "prevention:permits:view" },
    { roleSlug: "administrador",        permission: "prevention:permits:manage" },
    { roleSlug: "administrador",        permission: "prevention:permits:request" },
    { roleSlug: "administrador",        permission: "prevention:permits:verify" },
    { roleSlug: "administrador",        permission: "prevention:permits:approve" },
    { roleSlug: "administrador",        permission: "prevention:permits:activate" },
    { roleSlug: "administrador",        permission: "prevention:permits:suspend" },
    { roleSlug: "administrador",        permission: "prevention:permits:close" },
    { roleSlug: "administrador",        permission: "prevention:permits:export" },
    // Inspecciones. Ejecutar y revisar se separan: el servicio además impide
    // que quien ejecutó cierre su propia inspección.
    { roleSlug: "jefe_terreno",         permission: "prevention:inspections:view" },
    { roleSlug: "jefe_terreno",         permission: "prevention:inspections:execute" },
    { roleSlug: "admin_contrato",       permission: "prevention:inspections:view" },
    { roleSlug: "admin_contrato",       permission: "prevention:inspections:execute" },
    { roleSlug: "prevencionista_faena", permission: "prevention:inspections:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:inspections:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:inspections:execute" },
    { roleSlug: "prevencionista_faena", permission: "prevention:inspections:review" },
    { roleSlug: "prevencionista",       permission: "prevention:inspections:view" },
    { roleSlug: "prevencionista",       permission: "prevention:inspections:manage" },
    { roleSlug: "prevencionista",       permission: "prevention:inspections:approve" },
    { roleSlug: "prevencionista",       permission: "prevention:inspections:execute" },
    { roleSlug: "prevencionista",       permission: "prevention:inspections:review" },
    { roleSlug: "prevencionista",       permission: "prevention:inspections:export" },
    { roleSlug: "cphs",                 permission: "prevention:inspections:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:inspections:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:inspections:approve" },
    { roleSlug: "jefa_chome",           permission: "prevention:inspections:review" },
    { roleSlug: "jefa_chome",           permission: "prevention:inspections:export" },
    { roleSlug: "administrador",        permission: "prevention:inspections:view" },
    { roleSlug: "administrador",        permission: "prevention:inspections:manage" },
    { roleSlug: "administrador",        permission: "prevention:inspections:approve" },
    { roleSlug: "administrador",        permission: "prevention:inspections:execute" },
    { roleSlug: "administrador",        permission: "prevention:inspections:review" },
    { roleSlug: "administrador",        permission: "prevention:inspections:export" },
    // CPHS. El comité es un órgano propio: sus integrantes lo ven y lo
    // gestionan. La revisión por la dirección es de jefatura, no de terreno.
    { roleSlug: "cphs",                 permission: "prevention:cphs:view" },
    { roleSlug: "cphs",                 permission: "prevention:cphs:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:cphs:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:cphs:manage" },
    { roleSlug: "prevencionista",       permission: "prevention:cphs:view" },
    { roleSlug: "prevencionista",       permission: "prevention:cphs:manage" },
    { roleSlug: "jefe_terreno",         permission: "prevention:cphs:view" },
    { roleSlug: "admin_contrato",       permission: "prevention:cphs:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:cphs:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:cphs:manage" },
    { roleSlug: "jefa_chome",           permission: "prevention:governance:review" },
    { roleSlug: "administrador",        permission: "prevention:cphs:view" },
    { roleSlug: "administrador",        permission: "prevention:cphs:manage" },
    { roleSlug: "administrador",        permission: "prevention:governance:review" },
    // Higiene industrial. La vista es agregada y anonimizada, por eso puede
    // concederse ampliamente; el resultado clínico individual sigue viviendo
    // en el dominio sensible con sus propios permisos nominativos.
    { roleSlug: "prevencionista",       permission: "prevention:hygiene:view" },
    { roleSlug: "prevencionista",       permission: "prevention:hygiene:manage" },
    { roleSlug: "prevencionista",       permission: "prevention:hygiene:measure" },
    { roleSlug: "prevencionista_faena", permission: "prevention:hygiene:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:hygiene:measure" },
    { roleSlug: "cphs",                 permission: "prevention:hygiene:view" },
    { roleSlug: "jefe_terreno",         permission: "prevention:hygiene:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:hygiene:view" },
    { roleSlug: "jefa_chome",           permission: "prevention:hygiene:manage" },
    { roleSlug: "administrador",        permission: "prevention:hygiene:view" },
    { roleSlug: "administrador",        permission: "prevention:hygiene:manage" },
    { roleSlug: "administrador",        permission: "prevention:hygiene:measure" },
  ],
} as const satisfies ModuleManifest
