import type { ModuleManifest } from "@/modules/manifest-types"

export const preventionModule = {
  id: "prevention",

  permissions: [
    "prevention:pdtp:view",
    "prevention:pdtp:execute",
    "prevention:pdtp:program:manage",
    "prevention:pdtp:approve",
    "prevention:pdtp:sign_legal",
    "prevention:pdtp:checklist:manage",
    "prevention:pdtp:checklist:fill",
    "prevention:pdtp:action:manage",
    "prevention:pdtp:action:verify",
    "prevention:docs:view",
    "prevention:docs:manage",
    "prevention:docs:archive",
    "prevention:docs:manage_sensitive",
    "prevention:docs:manage_restricted",
    "prevention:indicadores:view",
    "prevention:indicadores:manage",
  ] as const,

  permissionMeta: {
    "prevention:pdtp:view":       { id: "p-prev-pdtp-view",       description: "Ver Programa de Trabajo Preventivo SG-SST" },
    "prevention:pdtp:execute":    { id: "p-prev-pdtp-execute",    description: "Registrar ejecuciones y evidencias del Programa de Trabajo Preventivo en faenas autorizadas" },
    "prevention:pdtp:program:manage": { id: "p-prev-pdtp-program-manage", description: "Administrar catálogo, cronograma y metas por faena del Programa de Trabajo Preventivo" },
    "prevention:pdtp:approve":    { id: "p-prev-pdtp-approve",    description: "Aprobar el Programa de Trabajo Preventivo como jefatura de prevención" },
    "prevention:pdtp:sign_legal": { id: "p-prev-pdtp-sign-legal", description: "Firmar el Programa de Trabajo Preventivo como Gerencia Legal y Recursos Humanos" },
    "prevention:pdtp:checklist:manage": { id: "p-prev-pdtp-cl-manage", description: "Crear/editar plantillas de checklist del PDTP" },
    "prevention:pdtp:checklist:fill":   { id: "p-prev-pdtp-cl-fill",   description: "Llenar el checklist de verificación en una ejecución del PDTP" },
    "prevention:pdtp:action:manage":    { id: "p-prev-pdtp-act-manage", description: "Crear/editar acciones correctivas y su seguimiento en el PDTP" },
    "prevention:pdtp:action:verify":    { id: "p-prev-pdtp-act-verify", description: "Verificar el cierre de acciones correctivas del PDTP" },
    "prevention:docs:view":               { id: "p-prev-docs-v",    description: "Ver la documentación preventiva" },
    "prevention:docs:manage":             { id: "p-prev-docs-m",    description: "Subir archivos, crear carpetas y crear versiones de documentos" },
    "prevention:docs:archive":            { id: "p-prev-docs-arch", description: "Archivar (soft delete) documentos" },
    "prevention:docs:manage_sensitive":   { id: "p-prev-docs-sens", description: "Gestionar documentos con confidencialidad 'sensible'" },
    "prevention:docs:manage_restricted":  { id: "p-prev-docs-rest", description: "Gestionar documentos con confidencialidad 'restringido'" },
    "prevention:indicadores:view":   { id: "p-prev-ind-view",   description: "Ver indicadores de accidentabilidad" },
    "prevention:indicadores:manage": { id: "p-prev-ind-manage", description: "Registrar/editar indicadores de accidentabilidad" },
  },

  nav: [
    {
      areaId: "prevencion",
      items: [
        {
          label: "Programa preventivo SG-SST",
          href: "/prevencion/pdtp",
          iconName: "ClipboardText",
          permissions: ["prevention:pdtp:view"],
        },
        {
          label: "Plan de acción PDTP",
          href: "/prevencion/pdtp/acciones",
          iconName: "CheckSquare",
          permissions: ["prevention:pdtp:view"],
        },
        {
          label: "Documentación",
          href: "/prevencion/documentacion",
          iconName: "FolderOpen",
          permissions: ["prevention:docs:view"],
        },
        {
          label: "Indicadores de accidentabilidad",
          href: "/prevencion/indicadores",
          iconName: "ChartLineUp",
          permissions: ["prevention:indicadores:view"],
        },
      ],
    },
  ],

  defaultGrants: [
    // PDTP
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:view" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:execute" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:program:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:approve" },
    { roleSlug: "jefa_chome",          permission: "prevention:pdtp:view" },
    { roleSlug: "jefa_chome",          permission: "prevention:pdtp:approve" },
    { roleSlug: "jefa_chome",          permission: "prevention:pdtp:sign_legal" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:execute" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:view" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:execute" },
    { roleSlug: "jefe_terreno",        permission: "prevention:pdtp:view" },
    { roleSlug: "jefe_terreno",        permission: "prevention:pdtp:execute" },
    { roleSlug: "cphs",                permission: "prevention:pdtp:view" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:view" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:execute" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:program:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:approve" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:sign_legal" },
    // PDTP — Checklist / Plan de acción / Seguimiento
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:checklist:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:pdtp:action:verify" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:checklist:fill" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:action:manage" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:checklist:fill" },
    { roleSlug: "admin_contrato",      permission: "prevention:pdtp:action:manage" },
    { roleSlug: "jefe_terreno",        permission: "prevention:pdtp:action:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:checklist:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:action:manage" },
    { roleSlug: "administrador",       permission: "prevention:pdtp:action:verify" },
    // Documentación
    { roleSlug: "prevencionista",      permission: "prevention:docs:view" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:manage" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:archive" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:manage_sensitive" },
    { roleSlug: "prevencionista",      permission: "prevention:docs:manage_restricted" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:manage" },
    { roleSlug: "jefa_chome",          permission: "prevention:docs:view" },
    { roleSlug: "jefe_terreno",        permission: "prevention:docs:view" },
    { roleSlug: "administrador",       permission: "prevention:docs:view" },
    { roleSlug: "administrador",       permission: "prevention:docs:manage" },
    { roleSlug: "administrador",       permission: "prevention:docs:archive" },
    { roleSlug: "administrador",       permission: "prevention:docs:manage_sensitive" },
    { roleSlug: "administrador",       permission: "prevention:docs:manage_restricted" },
    // Indicadores de accidentabilidad
    { roleSlug: "prevencionista",      permission: "prevention:indicadores:view" },
    { roleSlug: "prevencionista",      permission: "prevention:indicadores:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:indicadores:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:indicadores:manage" },
    { roleSlug: "jefa_chome",          permission: "prevention:indicadores:view" },
    { roleSlug: "cphs",                permission: "prevention:indicadores:view" },
    { roleSlug: "administrador",       permission: "prevention:indicadores:view" },
    { roleSlug: "administrador",       permission: "prevention:indicadores:manage" },
  ],
} as const satisfies ModuleManifest
