import type { ModuleManifest } from "@/modules/manifest-types"

/**
 * Modulo de Prevencion ampliado: matriz de riesgos, incidentes y capacitaciones.
 * Mantiene el area de navegacion 'prevencion' junto a SST y PPA.
 */
export const preventionModule = {
  id: "prevention",

  permissions: [
    "prevention:pdtp:view",
    "prevention:pdtp:manage",
    "prevention:pdtp:approve",
    "prevention:pdtp:sign_legal",
    "prevention:iper:view",
    "prevention:iper:manage",
    "prevention:incidents:view",
    "prevention:incidents:manage",
    "prevention:incidents:close",
    "prevention:training:view",
    "prevention:training:manage",
    "prevention:inspections:view",
    "prevention:inspections:manage",
    "prevention:inspections:close",
    "prevention:equipment_reports:view",
    "prevention:equipment_reports:manage",
    "prevention:alcohol_tests:view",
    "prevention:alcohol_tests:manage",
    "prevention:epp_matrix:view",
    "prevention:epp_matrix:manage",
    "prevention:epp_stock:view",
    "prevention:epp_stock:manage",
    "prevention:permits:view",
    "prevention:permits:manage",
    "prevention:health:view",
    "prevention:health:manage",
    "prevention:health:restrict",
    "prevention:emergency:view",
    "prevention:emergency:manage",
    "prevention:emergency:drill",
    "prevention:contractors:view",
    "prevention:contractors:manage",
    "prevention:cphs:view",
    "prevention:cphs:manage",
    "prevention:kpis:view",
    "prevention:kpis:export",
    "prevention:kpis:manage",
    "prevention:incident_procedure:view",
    "prevention:incident_procedure:manage",
    "prevention:incident_procedure:close",
    // Ola 5 — Biblioteca Documental Preventiva (SST)
    "prevention:docs:view",
    "prevention:docs:manage",
    "prevention:docs:approve",
    "prevention:docs:archive",
    "prevention:docs:ack",
    "prevention:docs:link",
    "prevention:docs:export",
    "prevention:docs:manage_sensitive",
    "prevention:docs:manage_restricted",
  ] as const,

  permissionMeta: {
    "prevention:pdtp:view":         { id: "p-prev-pdtp-view", description: "Ver Programa de Trabajo Preventivo SG-SST" },
    "prevention:pdtp:manage":       { id: "p-prev-pdtp-manage", description: "Gestionar catalogo, cronograma y ejecuciones del Programa de Trabajo Preventivo" },
    "prevention:pdtp:approve":      { id: "p-prev-pdtp-approve", description: "Aprobar el Programa de Trabajo Preventivo como jefatura de prevencion" },
    "prevention:pdtp:sign_legal":   { id: "p-prev-pdtp-sign-legal", description: "Firmar el Programa de Trabajo Preventivo como Gerencia Legal y Recursos Humanos" },
    "prevention:iper:view":          { id: "p-prev-iper-view",   description: "Ver matriz de identificacion de peligros y evaluacion de riesgos" },
    "prevention:iper:manage":        { id: "p-prev-iper-manage", description: "Gestionar matriz de identificacion de peligros y evaluacion de riesgos" },
    "prevention:incidents:view":     { id: "p-prev-inc-view",    description: "Ver accidentes, incidentes y cuasi accidentes" },
    "prevention:incidents:manage":   { id: "p-prev-inc-manage",  description: "Registrar y gestionar la investigacion de incidentes" },
    "prevention:incidents:close":    { id: "p-prev-inc-close",   description: "Cerrar investigaciones de incidentes" },
    "prevention:training:view":      { id: "p-prev-train-view",  description: "Ver capacitaciones y competencias" },
    "prevention:training:manage":    { id: "p-prev-train-manage", description: "Gestionar cursos y asignaciones de capacitacion" },
    "prevention:inspections:view":   { id: "p-prev-insp-view", description: "Ver inspecciones planificadas y observaciones conductuales" },
    "prevention:inspections:manage": { id: "p-prev-insp-manage", description: "Ejecutar inspecciones y registrar observaciones" },
    "prevention:inspections:close":  { id: "p-prev-insp-close", description: "Cerrar inspecciones con firma" },
    "prevention:equipment_reports:view":   { id: "p-prev-eq-view", description: "Ver reportes diarios de equipos y checklists" },
    "prevention:equipment_reports:manage": { id: "p-prev-eq-manage", description: "Registrar y revisar reportes de equipos" },
    "prevention:alcohol_tests:view":   { id: "p-prev-alc-view", description: "Ver registros de alcotest" },
    "prevention:alcohol_tests:manage": { id: "p-prev-alc-manage", description: "Registrar y enviar resultados de alcotest" },
    "prevention:epp_matrix:view":   { id: "p-prev-epp-v", description: "Ver matriz EPP por cargo y faena" },
    "prevention:epp_matrix:manage": { id: "p-prev-epp-m", description: "Gestionar matriz EPP y ciclo de vida" },
    "prevention:epp_stock:view":   { id: "p-prev-stock-v", description: "Ver umbrales de stock EPP" },
    "prevention:epp_stock:manage": { id: "p-prev-stock-m", description: "Configurar umbrales de stock EPP" },
    "prevention:permits:view":   { id: "p-prev-perm-v", description: "Ver permisos de trabajo" },
    "prevention:permits:manage": { id: "p-prev-perm-m", description: "Gestionar permisos de trabajo y AST" },
    "prevention:health:view":      { id: "p-prev-hlth-v", description: "Ver fichas de salud ocupacional" },
    "prevention:health:manage":    { id: "p-prev-hlth-m", description: "Registrar exámenes, aptitudes y protocolos MINSAL" },
    "prevention:health:restrict":  { id: "p-prev-hlth-r", description: "Registrar restricciones de salud" },
    "prevention:emergency:view":   { id: "p-prev-emer-v", description: "Ver planes de emergencia y simulacros" },
    "prevention:emergency:manage": { id: "p-prev-emer-m", description: "Gestionar planes, equipos y brigadas de emergencia" },
    "prevention:emergency:drill":  { id: "p-prev-emer-d", description: "Programar y ejecutar simulacros" },
    "prevention:contractors:view":   { id: "p-prev-ctr-v", description: "Ver contratistas" },
    "prevention:contractors:manage": { id: "p-prev-ctr-m", description: "Gestionar padrón y documentación de contratistas" },
    "prevention:cphs:view":   { id: "p-prev-cphs-v", description: "Ver comités y reuniones" },
    "prevention:cphs:manage": { id: "p-prev-cphs-m", description: "Gestionar comités, reuniones y acuerdos" },
    "prevention:kpis:view":   { id: "p-prev-kpi-v", description: "Ver indicadores preventivos" },
    "prevention:kpis:export": { id: "p-prev-kpi-e", description: "Exportar reportes de KPIs" },
    "prevention:kpis:manage": { id: "p-prev-kpi-m", description: "Registrar horas hombre trabajadas para el cálculo de tasas" },
    "prevention:incident_procedure:view":   { id: "p-prev-iproc-v", description: "Ver procedimiento completo de incidentes" },
    "prevention:incident_procedure:manage": { id: "p-prev-iproc-m", description: "Gestionar notificaciones, declaraciones e investigación" },
    "prevention:incident_procedure:close":  { id: "p-prev-iproc-c", description: "Cerrar investigaciones de incidentes" },
    // Ola 5 — Biblioteca Documental Preventiva (SST)
    "prevention:docs:view":               { id: "p-prev-docs-v",      description: "Ver la biblioteca documental SST" },
    "prevention:docs:manage":             { id: "p-prev-docs-m",      description: "Subir, editar metadata y crear versiones de documentos SST" },
    "prevention:docs:approve":            { id: "p-prev-docs-a",      description: "Aprobar, observar o archivar documentos SST" },
    "prevention:docs:archive":            { id: "p-prev-docs-arch",   description: "Archivar (soft delete) documentos SST" },
    "prevention:docs:ack":                { id: "p-prev-docs-ack",    description: "Registrar acuse de lectura / recepción de documentos SST" },
    "prevention:docs:link":               { id: "p-prev-docs-link",   description: "Asociar documentos SST con entidades internas (trabajador, faena, vehículo, etc.)" },
    "prevention:docs:export":             { id: "p-prev-docs-e",      description: "Exportar listados de la biblioteca SST (XLSX)" },
    "prevention:docs:manage_sensitive":   { id: "p-prev-docs-sens",   description: "Gestionar documentos con confidencialidad 'sensible'" },
    "prevention:docs:manage_restricted":  { id: "p-prev-docs-rest",   description: "Gestionar documentos con confidencialidad 'restringido'" },
  },

  nav: [
    {
      areaId: "prevencion",
      items: [
        {
          label: "Programa preventivo SG-SST",
          href: "/prevencion/pdtp",
          iconName: "ClipboardText",
          permissions: ["prevention:pdtp:view"],
        },
        {
          label: "Matriz de riesgos",
          href: "/prevencion/iper",
          iconName: "WarningDiamond",
          permissions: ["prevention:iper:view"],
        },
        {
          label: "Incidentes",
          href: "/prevencion/incidentes",
          iconName: "Siren",
          permissions: ["prevention:incidents:view"],
        },
        {
          label: "Capacitaciones",
          href: "/prevencion/capacitaciones",
          iconName: "Certificate",
          permissions: ["prevention:training:view"],
          children: [
            { label: "Matriz por cargo", href: "/prevencion/capacitaciones/matriz", permissions: ["prevention:training:view"] },
          ],
        },
        {
          label: "Inspecciones",
          href: "/prevencion/inspecciones",
          iconName: "MagnifyingGlass",
          permissions: ["prevention:inspections:view"],
        },
        {
          label: "Equipos",
          href: "/prevencion/equipos/reportes",
          iconName: "Truck",
          permissions: ["prevention:equipment_reports:view"],
        },
        {
          label: "Alcotest",
          href: "/prevencion/alcotest",
          iconName: "Drop",
          permissions: ["prevention:alcohol_tests:view"],
        },
        {
          label: "Matriz EPP",
          href: "/prevencion/epp/matriz",
          iconName: "HardHat",
          permissions: ["prevention:epp_matrix:view"],
          children: [
            { label: "Stock crítico", href: "/prevencion/epp/stock", permissions: ["prevention:epp_stock:view"] },
          ],
        },
        {
          label: "Salud ocupacional",
          href: "/prevencion/salud",
          iconName: "Heartbeat",
          permissions: ["prevention:health:view"],
          children: [
            { label: "Protocolos MINSAL", href: "/prevencion/salud/protocolos", permissions: ["prevention:health:view"] },
          ],
        },
        {
          label: "Emergencias",
          href: "/prevencion/emergencias",
          iconName: "Fire",
          permissions: ["prevention:emergency:view"],
        },
        {
          label: "Biblioteca SST",
          href: "/prevencion/biblioteca",
          iconName: "Books",
          permissions: ["prevention:docs:view"],
          children: [
            { label: "Bandeja de revisión", href: "/prevencion/biblioteca/revisiones", permissions: ["prevention:docs:approve"] },
            { label: "Vencimientos",       href: "/prevencion/biblioteca/vencimientos", permissions: ["prevention:docs:view"] },
          ],
        },
        {
          label: "Contratistas",
          href: "/prevencion/contratistas",
          iconName: "UsersThree",
          permissions: ["prevention:contractors:view"],
        },
        {
          label: "Comités",
          href: "/prevencion/comites",
          iconName: "ChatsCircle",
          permissions: ["prevention:cphs:view"],
        },
        {
          label: "KPIs",
          href: "/prevencion/kpis",
          iconName: "ChartBar",
          permissions: ["prevention:kpis:view"],
        },
        {
          label: "Permisos de trabajo",
          href: "/prevencion/permisos",
          iconName: "HardHat",
          permissions: ["prevention:permits:view"],
        },
      ],
    },
  ],

  defaultGrants: [
    // Prevencion de oficina: acceso completo al modulo.
    { roleSlug: "prevencionista", permission: "prevention:pdtp:view" },
    { roleSlug: "prevencionista", permission: "prevention:pdtp:manage" },
    { roleSlug: "prevencionista", permission: "prevention:pdtp:approve" },
    { roleSlug: "prevencionista", permission: "prevention:iper:view" },
    { roleSlug: "prevencionista", permission: "prevention:iper:manage" },
    { roleSlug: "prevencionista", permission: "prevention:incidents:view" },
    { roleSlug: "prevencionista", permission: "prevention:incidents:manage" },
    { roleSlug: "prevencionista", permission: "prevention:incidents:close" },
    { roleSlug: "prevencionista", permission: "prevention:training:view" },
    { roleSlug: "prevencionista", permission: "prevention:training:manage" },
    // Gerencia Legal/Recursos Humanos y jefatura: firma legal y visibilidad ejecutiva.
    { roleSlug: "jefa_chome", permission: "prevention:pdtp:view" },
    { roleSlug: "jefa_chome", permission: "prevention:pdtp:approve" },
    { roleSlug: "jefa_chome", permission: "prevention:pdtp:sign_legal" },
    // Prevencionista de faena: alcance acotado a sus faenas.
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:pdtp:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:iper:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incidents:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:training:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:training:manage" },
    // Roles de terreno incorporados por el PDTP.
    { roleSlug: "admin_contrato", permission: "prevention:pdtp:view" },
    { roleSlug: "admin_contrato", permission: "prevention:pdtp:manage" },
    { roleSlug: "supervisor_faena", permission: "prevention:pdtp:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:pdtp:manage" },
    { roleSlug: "jefe_terreno", permission: "prevention:pdtp:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:pdtp:manage" },
    { roleSlug: "cphs", permission: "prevention:pdtp:view" },
    // Administrador: control total.
    { roleSlug: "administrador", permission: "prevention:pdtp:view" },
    { roleSlug: "administrador", permission: "prevention:pdtp:manage" },
    { roleSlug: "administrador", permission: "prevention:pdtp:approve" },
    { roleSlug: "administrador", permission: "prevention:pdtp:sign_legal" },
    { roleSlug: "administrador", permission: "prevention:iper:view" },
    { roleSlug: "administrador", permission: "prevention:iper:manage" },
    { roleSlug: "administrador", permission: "prevention:incidents:view" },
    { roleSlug: "administrador", permission: "prevention:incidents:manage" },
    { roleSlug: "administrador", permission: "prevention:incidents:close" },
    { roleSlug: "administrador", permission: "prevention:training:view" },
    { roleSlug: "administrador", permission: "prevention:training:manage" },
    // Ola 2 — Inspecciones, equipos, alcotest, EPP
    { roleSlug: "prevencionista", permission: "prevention:inspections:view" },
    { roleSlug: "prevencionista", permission: "prevention:inspections:manage" },
    { roleSlug: "prevencionista", permission: "prevention:inspections:close" },
    { roleSlug: "prevencionista", permission: "prevention:equipment_reports:view" },
    { roleSlug: "prevencionista", permission: "prevention:equipment_reports:manage" },
    { roleSlug: "prevencionista", permission: "prevention:alcohol_tests:view" },
    { roleSlug: "prevencionista", permission: "prevention:alcohol_tests:manage" },
    { roleSlug: "prevencionista", permission: "prevention:epp_matrix:view" },
    { roleSlug: "prevencionista", permission: "prevention:epp_matrix:manage" },
    { roleSlug: "prevencionista", permission: "prevention:epp_stock:view" },
    { roleSlug: "prevencionista", permission: "prevention:epp_stock:manage" },
    { roleSlug: "prevencionista", permission: "prevention:permits:view" },
    { roleSlug: "prevencionista", permission: "prevention:permits:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:inspections:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:inspections:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:equipment_reports:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:equipment_reports:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:alcohol_tests:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:alcohol_tests:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:epp_matrix:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:epp_stock:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:permits:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:inspections:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:inspections:manage" },
    { roleSlug: "supervisor_faena", permission: "prevention:equipment_reports:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:equipment_reports:manage" },
    { roleSlug: "supervisor_faena", permission: "prevention:alcohol_tests:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:alcohol_tests:manage" },
    { roleSlug: "supervisor_faena", permission: "prevention:permits:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:inspections:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:inspections:manage" },
    { roleSlug: "jefe_terreno", permission: "prevention:equipment_reports:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:equipment_reports:manage" },
    { roleSlug: "jefe_terreno", permission: "prevention:alcohol_tests:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:alcohol_tests:manage" },
    { roleSlug: "jefe_terreno", permission: "prevention:permits:view" },
    { roleSlug: "cphs", permission: "prevention:inspections:view" },
    // Ola 3+4 — Salud, emergencias, contratistas, comités, KPIs, incidentes
    { roleSlug: "prevencionista", permission: "prevention:health:view" },
    { roleSlug: "prevencionista", permission: "prevention:health:manage" },
    { roleSlug: "prevencionista", permission: "prevention:health:restrict" },
    { roleSlug: "prevencionista", permission: "prevention:emergency:view" },
    { roleSlug: "prevencionista", permission: "prevention:emergency:manage" },
    { roleSlug: "prevencionista", permission: "prevention:emergency:drill" },
    { roleSlug: "prevencionista", permission: "prevention:contractors:view" },
    { roleSlug: "prevencionista", permission: "prevention:contractors:manage" },
    { roleSlug: "prevencionista", permission: "prevention:cphs:view" },
    { roleSlug: "prevencionista", permission: "prevention:cphs:manage" },
    { roleSlug: "prevencionista", permission: "prevention:kpis:view" },
    { roleSlug: "prevencionista", permission: "prevention:kpis:export" },
    { roleSlug: "prevencionista", permission: "prevention:kpis:manage" },
    { roleSlug: "prevencionista", permission: "prevention:incident_procedure:view" },
    { roleSlug: "prevencionista", permission: "prevention:incident_procedure:manage" },
    { roleSlug: "prevencionista", permission: "prevention:incident_procedure:close" },
    { roleSlug: "jefa_chome", permission: "prevention:kpis:view" },
    { roleSlug: "jefa_chome", permission: "prevention:kpis:export" },
    { roleSlug: "prevencionista_faena", permission: "prevention:health:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:emergency:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:contractors:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:cphs:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:kpis:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incident_procedure:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:incident_procedure:manage" },
    { roleSlug: "supervisor_faena", permission: "prevention:health:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:emergency:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:contractors:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:kpis:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:incident_procedure:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:health:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:emergency:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:emergency:manage" },
    { roleSlug: "jefe_terreno", permission: "prevention:contractors:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:kpis:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:incident_procedure:view" },
    { roleSlug: "cphs", permission: "prevention:cphs:view" },
    { roleSlug: "cphs", permission: "prevention:cphs:manage" },
    { roleSlug: "cphs", permission: "prevention:kpis:view" },
    // Administrador: control total (ampliado — ola 2/3/4).
    { roleSlug: "administrador", permission: "prevention:inspections:view" },
    { roleSlug: "administrador", permission: "prevention:inspections:manage" },
    { roleSlug: "administrador", permission: "prevention:inspections:close" },
    { roleSlug: "administrador", permission: "prevention:equipment_reports:view" },
    { roleSlug: "administrador", permission: "prevention:equipment_reports:manage" },
    { roleSlug: "administrador", permission: "prevention:alcohol_tests:view" },
    { roleSlug: "administrador", permission: "prevention:alcohol_tests:manage" },
    { roleSlug: "administrador", permission: "prevention:epp_matrix:view" },
    { roleSlug: "administrador", permission: "prevention:epp_matrix:manage" },
    { roleSlug: "administrador", permission: "prevention:epp_stock:view" },
    { roleSlug: "administrador", permission: "prevention:epp_stock:manage" },
    { roleSlug: "administrador", permission: "prevention:permits:view" },
    { roleSlug: "administrador", permission: "prevention:permits:manage" },
    { roleSlug: "administrador", permission: "prevention:health:view" },
    { roleSlug: "administrador", permission: "prevention:health:manage" },
    { roleSlug: "administrador", permission: "prevention:health:restrict" },
    { roleSlug: "administrador", permission: "prevention:emergency:view" },
    { roleSlug: "administrador", permission: "prevention:emergency:manage" },
    { roleSlug: "administrador", permission: "prevention:emergency:drill" },
    { roleSlug: "administrador", permission: "prevention:contractors:view" },
    { roleSlug: "administrador", permission: "prevention:contractors:manage" },
    { roleSlug: "administrador", permission: "prevention:cphs:view" },
    { roleSlug: "administrador", permission: "prevention:cphs:manage" },
    { roleSlug: "administrador", permission: "prevention:kpis:view" },
    { roleSlug: "administrador", permission: "prevention:kpis:export" },
    { roleSlug: "administrador", permission: "prevention:kpis:manage" },
    { roleSlug: "administrador", permission: "prevention:incident_procedure:view" },
    { roleSlug: "administrador", permission: "prevention:incident_procedure:manage" },
    { roleSlug: "administrador", permission: "prevention:incident_procedure:close" },
    // Ola 5 — Biblioteca Documental Preventiva (SST)
    { roleSlug: "prevencionista", permission: "prevention:docs:view" },
    { roleSlug: "prevencionista", permission: "prevention:docs:manage" },
    { roleSlug: "prevencionista", permission: "prevention:docs:approve" },
    { roleSlug: "prevencionista", permission: "prevention:docs:archive" },
    { roleSlug: "prevencionista", permission: "prevention:docs:ack" },
    { roleSlug: "prevencionista", permission: "prevention:docs:link" },
    { roleSlug: "prevencionista", permission: "prevention:docs:export" },
    { roleSlug: "prevencionista", permission: "prevention:docs:manage_sensitive" },
    { roleSlug: "prevencionista", permission: "prevention:docs:manage_restricted" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:view" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:manage" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:ack" },
    { roleSlug: "prevencionista_faena", permission: "prevention:docs:link" },
    { roleSlug: "jefa_chome", permission: "prevention:docs:view" },
    { roleSlug: "jefa_chome", permission: "prevention:docs:approve" },
    { roleSlug: "jefa_chome", permission: "prevention:docs:export" },
    { roleSlug: "jefa_chome", permission: "prevention:docs:ack" },
    { roleSlug: "supervisor_faena", permission: "prevention:docs:view" },
    { roleSlug: "supervisor_faena", permission: "prevention:docs:ack" },
    { roleSlug: "jefe_terreno", permission: "prevention:docs:view" },
    { roleSlug: "jefe_terreno", permission: "prevention:docs:ack" },
    { roleSlug: "administrador", permission: "prevention:docs:view" },
    { roleSlug: "administrador", permission: "prevention:docs:manage" },
    { roleSlug: "administrador", permission: "prevention:docs:approve" },
    { roleSlug: "administrador", permission: "prevention:docs:archive" },
    { roleSlug: "administrador", permission: "prevention:docs:ack" },
    { roleSlug: "administrador", permission: "prevention:docs:link" },
    { roleSlug: "administrador", permission: "prevention:docs:export" },
    { roleSlug: "administrador", permission: "prevention:docs:manage_sensitive" },
    { roleSlug: "administrador", permission: "prevention:docs:manage_restricted" },
  ],
} as const satisfies ModuleManifest
