"use client"

import { useState, useTransition, type FormEvent, type ReactNode } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { DatePicker } from "@/components/ui/date-picker"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { EmptyState } from "@/components/ui/empty-state"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import {
  LEGAL_APPLICABILITY_STATUS_LABELS,
  LEGAL_COMPLIANCE_STATUS_LABELS,
  LEGAL_REQUIREMENT_STATUS_LABELS,
  legalStatusVariant,
} from "@/lib/prevention/badges"
import { formatDate, todayInChile } from "@/lib/utils"
import type { getLegalDashboard } from "@/lib/services/prevention-risk-legal"
import {
  approveLegalApplicabilityAction,
  assessLegalComplianceAction,
  createLegalRequirementDraftAction,
  proposeLegalApplicabilityAction,
  transitionLegalRequirementAction,
} from "./actions"

type Dashboard = Awaited<ReturnType<typeof getLegalDashboard>>
type Result = { ok: boolean; message?: string }

function useOperation() {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("")
  function run(operation: () => Promise<Result>, success?: () => void) { setMessage(""); startTransition(async () => { const result = await operation(); setMessage(result.ok ? "Guardado correctamente." : result.message ?? "No se pudo completar la acción."); if (result.ok) success?.() }) }
  return { pending, message, run }
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1 text-sm"><span className="font-medium">{label}</span>{children}</label> }

export function LegalRequirementsHeaderActions({ canAssess, canExport }: { canAssess: boolean; canExport: boolean }) {
  return <div className="flex gap-2">{canExport && <Button asChild variant="secondary"><a href="/api/prevencion/requisitos-legales/export" download>Exportar Excel</a></Button>}{canAssess && <CreateRequirementDialog />}</div>
}

function CreateRequirementDialog() {
  const [open, setOpen] = useState(false); const [sourceType, setSourceType] = useState("legal"); const operation = useOperation()
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const v = new FormData(event.currentTarget); operation.run(() => createLegalRequirementDraftAction({ code: v.get("code"), sourceType: v.get("sourceType"), authority: v.get("authority"), sourceTitle: v.get("sourceTitle"), sourceReference: v.get("sourceReference"), sourceUrl: v.get("sourceUrl") || null, article: v.get("article"), requirement: v.get("requirement"), versionLabel: v.get("versionLabel"), validFrom: v.get("validFrom"), topic: v.get("topic"), chomeRole: v.get("chomeRole"), evidenceRequired: v.get("evidenceRequired"), frequency: v.get("frequency") }), () => setOpen(false)) }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button>Nuevo requisito</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><form onSubmit={submit} className="space-y-4"><DialogHeader><DialogTitle>Nuevo requisito</DialogTitle><DialogDescription>Registra una obligación granular. Su contenido y aplicabilidad deben pasar revisión segregada.</DialogDescription></DialogHeader><div className="grid gap-3 md:grid-cols-2"><Field label="Código"><Input name="code" required /></Field><Field label="Tipo de fuente"><Select value={sourceType} onValueChange={setSourceType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="legal">Ley</SelectItem><SelectItem value="regulatory">Reglamento</SelectItem><SelectItem value="contractual">Contrato</SelectItem><SelectItem value="standard">Norma voluntaria/contractual</SelectItem><SelectItem value="internal">Política interna</SelectItem></SelectContent></Select><input type="hidden" name="sourceType" value={sourceType} /></Field><Field label="Autoridad / contraparte"><Input name="authority" required /></Field><Field label="Título de la fuente"><Input name="sourceTitle" required /></Field><Field label="Referencia"><Input name="sourceReference" required /></Field><Field label="URL oficial"><Input name="sourceUrl" type="url" /></Field><Field label="Artículo / cláusula"><Input name="article" required /></Field><Field label="Versión"><Input name="versionLabel" required /></Field><Field label="Vigente desde"><DatePicker name="validFrom" defaultValue={todayInChile()} /></Field><Field label="Tema"><Input name="topic" required /></Field></div><Field label="Requisito"><Textarea name="requirement" required minLength={10} /></Field><Field label="Rol de Chome"><Textarea name="chomeRole" required /></Field><Field label="Evidencia requerida"><Textarea name="evidenceRequired" required /></Field><Field label="Frecuencia"><Input name="frequency" required /></Field>{operation.message && <p role="status" className="text-sm">{operation.message}</p>}<DialogFooter><Button type="submit" disabled={operation.pending}>Crear borrador</Button></DialogFooter></form></DialogContent></Dialog>
}

export function LegalRequirementsWorkbench({ dashboard, worksites, processes, canAssess, canApprove }: {
  dashboard: Dashboard
  worksites: Dashboard["worksites"]
  processes: Dashboard["processes"]
  canAssess: boolean
  canApprove: boolean
  canExport: boolean
}) {
  // Los contadores los calcula el servicio: la vigencia del requisito es lo que
  // decide si una aplicabilidad cuenta, y recalcularla acá volvía a contar
  // obligaciones derogadas (LEGAL-01).
  const counts = dashboard.counts
  return <div className="space-y-4"><div className="grid grid-cols-2 overflow-hidden border-y lg:grid-cols-4"><a href="#requisitos" className="border-r px-4 py-3 hover:bg-[var(--color-surface-2)]"><span className="text-eyebrow">Requisitos vigentes</span><strong className="block text-xl">{counts.requirementsInForce}</strong></a><a href="#aplicabilidad" className="border-r px-4 py-3 hover:bg-[var(--color-surface-2)]"><span className="text-eyebrow">Aplicables</span><strong className="block text-xl">{counts.applicable}</strong>{counts.superseded > 0 && <span className="block text-xs text-[var(--color-text-subtle)]">{counts.superseded} por re-evaluar</span>}</a><a href="#brechas" className="border-r px-4 py-3 hover:bg-[var(--color-surface-2)]"><span className="text-eyebrow">Con evidencia y cumplimiento</span><strong className="block text-xl">{counts.compliant}/{counts.applicable}</strong></a><a href="#aplicabilidad" className="px-4 py-3 hover:bg-[var(--color-surface-2)]"><span className="text-eyebrow">Aprobaciones pendientes</span><strong className="block text-xl">{counts.pendingApproval}</strong></a></div>
    <Tabs defaultValue="requirements"><TabsList><TabsTrigger value="requirements">Registro legal</TabsTrigger><TabsTrigger value="applicability">Aplicabilidad ({dashboard.applicabilities.length})</TabsTrigger><TabsTrigger value="gaps">Brechas ({dashboard.gaps.length})</TabsTrigger></TabsList>
      <TabsContent value="requirements" id="requisitos" className="space-y-3">{dashboard.requirements.length === 0 ? <EmptyState title="Sin requisitos registrados" description="Crea requisitos por artículo o cláusula, no sólo por nombre de norma." /> : dashboard.requirements.map((requirement) => <section key={requirement.id} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex gap-2"><strong>{requirement.code} · {requirement.article}</strong><Badge variant={legalStatusVariant(requirement.inForce ? requirement.status : "superseded")}>{requirement.status === "published" && !requirement.inForce ? "Vigencia terminada" : LEGAL_REQUIREMENT_STATUS_LABELS[requirement.status] ?? requirement.status}</Badge></div><p className="mt-1 text-sm">{requirement.requirement}</p><p className="mt-1 text-xs text-[var(--color-text-subtle)]">{requirement.authority} · {requirement.sourceReference} · v{requirement.requirementVersion} · vigencia {formatDate(requirement.validFrom)}{requirement.validTo ? ` a ${formatDate(requirement.validTo)}` : " en adelante"}</p></div><div className="flex gap-2"><RequirementTransition requirement={requirement} canAssess={canAssess} canApprove={canApprove} />{requirement.inForce && canAssess && <ApplicabilityDialog requirementId={requirement.id} worksites={worksites} processes={processes} />}</div></div></section>)}</TabsContent>
      <TabsContent value="applicability" id="aplicabilidad" className="space-y-3">{dashboard.applicabilities.length === 0 ? <EmptyState title="Sin decisiones de aplicabilidad" description="Propón por faena si cada requisito vigente aplica o no, con fundamento." /> : dashboard.applicabilities.map(({ applicability, requirement, worksiteName, inForce }) => <section key={applicability.id} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex gap-2"><strong>{requirement.code} · {worksiteName}</strong><Badge variant={legalStatusVariant(applicability.applicabilityStatus)}>{LEGAL_APPLICABILITY_STATUS_LABELS[applicability.applicabilityStatus] ?? applicability.applicabilityStatus}</Badge><Badge variant={legalStatusVariant(applicability.complianceStatus)}>{LEGAL_COMPLIANCE_STATUS_LABELS[applicability.complianceStatus] ?? applicability.complianceStatus}</Badge>{!inForce && <Badge variant="outline">Requisito no vigente · re-evaluar</Badge>}</div><p className="mt-1 text-sm">{applicability.rationale}</p><p className="mt-1 text-xs text-[var(--color-text-subtle)]">Responsable: {applicability.responsibleSnapshot} · Evidencia: {applicability.evidenceReference ?? "pendiente"}</p></div><div className="flex gap-2">{applicability.applicabilityStatus.startsWith("proposed_") && canApprove && <ApprovalDialog applicability={applicability} />}{inForce && applicability.applicabilityStatus === "applicable" && canAssess && <ComplianceDialog applicability={applicability} requirement={requirement} />}</div></div></section>)}</TabsContent>
      <TabsContent value="gaps" id="brechas" className="space-y-3">{dashboard.gaps.length === 0 ? <EmptyState title="Sin brechas en el alcance visible" description="Los requisitos aplicables tienen evidencia y evaluación vigente." /> : dashboard.gaps.map(({ applicability, requirement, worksiteName, gapReason }) => <div key={applicability.id} className="rounded-lg border border-[var(--color-danger-line)] p-4"><strong>{requirement.code} · {worksiteName}</strong><p className="mt-1 text-sm">{gapReason} · {applicability.evidenceReference ? "evidencia registrada" : "sin evidencia"}</p></div>)}</TabsContent>
    </Tabs></div>
}

function RequirementTransition({ requirement, canAssess, canApprove }: { requirement: Dashboard["requirements"][number]; canAssess: boolean; canApprove: boolean }) {
  const next = requirement.status === "draft" && canAssess ? ["in_review", "Enviar"] : requirement.status === "in_review" && canAssess ? ["reviewed", "Revisar"] : requirement.status === "reviewed" && canApprove ? ["approved", "Aprobar"] : requirement.status === "approved" && canApprove ? ["published", "Publicar"] : null
  const [open, setOpen] = useState(false); const operation = useOperation(); if (!next) return null
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const v = new FormData(event.currentTarget); operation.run(() => transitionLegalRequirementAction({ requirementId: requirement.id, expectedVersion: requirement.version, toStatus: next![0], reason: v.get("reason") }), () => setOpen(false)) }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="secondary">{next[1]}</Button></DialogTrigger><DialogContent><form onSubmit={submit} className="space-y-4"><DialogHeader><DialogTitle>{next[1]} requisito</DialogTitle><DialogDescription>La segregación también se verifica en el servidor.</DialogDescription></DialogHeader><Field label="Fundamento"><Textarea name="reason" required minLength={10} /></Field>{operation.message && <p role="status" className="text-sm">{operation.message}</p>}<DialogFooter><Button type="submit" disabled={operation.pending}>{next[1]}</Button></DialogFooter></form></DialogContent></Dialog>
}

function ApplicabilityDialog({ requirementId, worksites, processes }: { requirementId: string; worksites: Dashboard["worksites"]; processes: Dashboard["processes"] }) {
  const [open, setOpen] = useState(false); const [worksiteId, setWorksiteId] = useState(worksites[0]?.id ?? ""); const [processId, setProcessId] = useState(""); const [status, setStatus] = useState("proposed_applicable"); const operation = useOperation()
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const v = new FormData(event.currentTarget); operation.run(() => proposeLegalApplicabilityAction({ requirementId, worksiteId: v.get("worksiteId"), processId: v.get("processId") || null, activityReference: v.get("activityReference") || null, applicabilityStatus: v.get("status"), rationale: v.get("rationale"), responsibleSnapshot: v.get("responsible"), evidenceReference: v.get("evidence") || null, evidenceDueAt: v.get("evidenceDueAt") || null }), () => setOpen(false)) }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm">Evaluar aplicabilidad</Button></DialogTrigger><DialogContent><form onSubmit={submit} className="space-y-4"><DialogHeader><DialogTitle>Proponer aplicabilidad</DialogTitle><DialogDescription>Una decisión de no aplicabilidad exige fundamento y aprobador diferente.</DialogDescription></DialogHeader><Field label="Faena"><Select value={worksiteId} onValueChange={setWorksiteId}><SelectTrigger><SelectValue placeholder="Selecciona faena" /></SelectTrigger><SelectContent>{worksites.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select><input type="hidden" name="worksiteId" value={worksiteId} /></Field><Field label="Proceso opcional"><Select value={processId} onValueChange={(v) => setProcessId(v === "_none" ? "" : v)}><SelectTrigger><SelectValue placeholder="Toda la faena" /></SelectTrigger><SelectContent><SelectItem value="_none">Toda la faena</SelectItem>{processes.filter((item) => item.worksiteId === worksiteId).map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select><input type="hidden" name="processId" value={processId} /></Field><Field label="Actividad / alcance"><Input name="activityReference" /></Field><Field label="Decisión"><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="proposed_applicable">Aplicable</SelectItem><SelectItem value="proposed_not_applicable">No aplicable</SelectItem></SelectContent></Select><input type="hidden" name="status" value={status} /></Field><Field label="Fundamento"><Textarea name="rationale" required minLength={10} /></Field><Field label="Responsable"><Input name="responsible" required /></Field><Field label="Evidencia existente"><Input name="evidence" /></Field><Field label="Fecha límite de evidencia"><DatePicker name="evidenceDueAt" /></Field>{operation.message && <p role="status" className="text-sm">{operation.message}</p>}<DialogFooter><Button type="submit" disabled={operation.pending}>Enviar a aprobación</Button></DialogFooter></form></DialogContent></Dialog>
}

function ApprovalDialog({ applicability }: { applicability: Dashboard["applicabilities"][number]["applicability"] }) {
  const [open, setOpen] = useState(false); const operation = useOperation()
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const v = new FormData(event.currentTarget); operation.run(() => approveLegalApplicabilityAction({ applicabilityId: applicability.id, expectedVersion: applicability.version, reason: v.get("reason") }), () => setOpen(false)) }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm">Aprobar decisión</Button></DialogTrigger><DialogContent><form onSubmit={submit} className="space-y-4"><DialogHeader><DialogTitle>Aprobar aplicabilidad</DialogTitle><DialogDescription>Confirma la decisión y su fundamento; no podrás aprobar tu propia evaluación.</DialogDescription></DialogHeader><Field label="Fundamento de aprobación"><Textarea name="reason" required minLength={10} /></Field>{operation.message && <p role="status" className="text-sm">{operation.message}</p>}<DialogFooter><Button type="submit" disabled={operation.pending}>Aprobar</Button></DialogFooter></form></DialogContent></Dialog>
}

function ComplianceDialog({ applicability, requirement }: { applicability: Dashboard["applicabilities"][number]["applicability"]; requirement: Dashboard["applicabilities"][number]["requirement"] }) {
  const [open, setOpen] = useState(false); const [status, setStatus] = useState("compliant"); const [priority, setPriority] = useState("high"); const operation = useOperation(); const gap = status !== "compliant"
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const v = new FormData(event.currentTarget); operation.run(() => assessLegalComplianceAction({ applicabilityId: applicability.id, expectedVersion: applicability.version, status, finding: v.get("finding") || null, evidenceReference: v.get("evidence") || null, nextAssessmentAt: v.get("nextAssessmentAt") || null, capa: gap ? { actionDescription: v.get("action"), responsibleSnapshot: v.get("responsible"), targetDate: v.get("targetDate"), priority: v.get("priority") } : null }), () => setOpen(false)) }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="secondary">Evaluar cumplimiento</Button></DialogTrigger><DialogContent><form onSubmit={submit} className="space-y-4"><DialogHeader><DialogTitle>Evaluar {requirement.code}</DialogTitle><DialogDescription>Una brecha crea una CAPA común en la misma transacción.</DialogDescription></DialogHeader><Field label="Resultado"><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="compliant">Cumple</SelectItem><SelectItem value="partial">Cumplimiento parcial</SelectItem><SelectItem value="noncompliant">No cumple</SelectItem></SelectContent></Select></Field><Field label="Evidencia"><Input name="evidence" /></Field><Field label="Próxima evaluación"><DatePicker name="nextAssessmentAt" /></Field>{gap && <><Field label="Hallazgo"><Textarea name="finding" required minLength={5} /></Field><Field label="Acción CAPA"><Textarea name="action" required minLength={5} /></Field><Field label="Responsable"><Input name="responsible" required /></Field><Field label="Prioridad"><Select value={priority} onValueChange={setPriority}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="high">Alta</SelectItem><SelectItem value="critical">Crítica</SelectItem><SelectItem value="medium">Media</SelectItem></SelectContent></Select><input type="hidden" name="priority" value={priority} /></Field><Field label="Fecha objetivo"><DatePicker name="targetDate" /></Field></>}{operation.message && <p role="status" className="text-sm">{operation.message}</p>}<DialogFooter><Button type="submit" disabled={operation.pending}>Guardar evaluación</Button></DialogFooter></form></DialogContent></Dialog>
}
