"use server"

import { revalidatePath } from "next/cache"
import { eq } from "drizzle-orm"
import { z } from "zod"
import { db } from "@/db"
import { fuelStorageLocations } from "@/db/schema"
import { recordAudit } from "@/lib/audit"
import { requirePermission } from "@/lib/auth/can"
import { nanoid } from "@/lib/id"
import type { ActionState } from "@/lib/validation/masters"

const PATH = "/admin/flota-catalogos/estanques-combustible"
const locationSchema = z.object({ worksiteId: z.string().min(1, "Selecciona una faena"), productId: z.string().min(1, "Selecciona un producto"), name: z.string().trim().min(2, "Indica un nombre").max(120), capacityLiters: z.coerce.number().positive("La capacidad debe ser mayor a cero").optional(), notes: z.string().trim().max(1000).optional() })
function data(formData: FormData) { const capacity = String(formData.get("capacityLiters") ?? "").trim(); return { worksiteId: String(formData.get("worksiteId") ?? ""), productId: String(formData.get("productId") ?? ""), name: String(formData.get("name") ?? ""), capacityLiters: capacity || undefined, notes: String(formData.get("notes") ?? "").trim() || undefined } }
async function sessionOrError() { try { return { session: await requirePermission("admin:fleet_catalog") } } catch { return { error: { ok: false as const, message: "No tienes permisos para administrar estanques" } } } }
export async function createFuelStorageLocationAction(_prev: ActionState, formData: FormData): Promise<ActionState> { const access = await sessionOrError(); if (!access.session) return access.error!; const parsed = locationSchema.safeParse(data(formData)); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "Revisa los datos" }; const id = `fuel-storage-${nanoid()}`; try { await db.transaction(async tx => { await tx.insert(fuelStorageLocations).values({ id, ...parsed.data }); await recordAudit({ userId: access.session.user.id, userEmail: access.session.user.email ?? undefined, action: "create", entityType: "fuel_storage_location", entityId: id, newState: parsed.data }, tx) }); revalidatePath(PATH); revalidatePath("/combustibles/ciclo"); return { ok: true, message: "Estanque creado" } } catch { return { ok: false, message: "No se pudo crear: ya existe un estanque con ese nombre en la faena" } } }
export async function updateFuelStorageLocationAction(_prev: ActionState, formData: FormData): Promise<ActionState> { const access = await sessionOrError(); if (!access.session) return access.error!; const id = String(formData.get("id") ?? ""); const parsed = locationSchema.safeParse(data(formData)); if (!id || !parsed.success) return { ok: false, message: parsed.error?.issues[0]?.message ?? "Revisa los datos" }; const current = await db.query.fuelStorageLocations.findFirst({ where: eq(fuelStorageLocations.id, id) }); if (!current) return { ok: false, message: "Estanque no encontrado" }; const next = { ...parsed.data, updatedAt: new Date().toISOString() }; try { await db.transaction(async tx => { await tx.update(fuelStorageLocations).set(next).where(eq(fuelStorageLocations.id, id)); await recordAudit({ userId: access.session.user.id, userEmail: access.session.user.email ?? undefined, action: "update", entityType: "fuel_storage_location", entityId: id, oldState: current, newState: next }, tx) }); revalidatePath(PATH); revalidatePath("/combustibles/ciclo"); return { ok: true, message: "Estanque actualizado" } } catch { return { ok: false, message: "No se pudo actualizar el estanque" } } }
export async function setFuelStorageLocationStatusAction(id: string, isActive: boolean): Promise<ActionState> { const access = await sessionOrError(); if (!access.session) return access.error!; const current = await db.query.fuelStorageLocations.findFirst({ where: eq(fuelStorageLocations.id, id) }); if (!current) return { ok: false, message: "Estanque no encontrado" }; try { await db.transaction(async tx => { await tx.update(fuelStorageLocations).set({ isActive, updatedAt: new Date().toISOString() }).where(eq(fuelStorageLocations.id, id)); await recordAudit({ userId: access.session.user.id, userEmail: access.session.user.email ?? undefined, action: "update", entityType: "fuel_storage_location", entityId: id, oldState: { isActive: current.isActive }, newState: { isActive } }, tx) }); revalidatePath(PATH); revalidatePath("/combustibles/ciclo"); return { ok: true, message: isActive ? "Estanque activado" : "Estanque desactivado" } } catch { return { ok: false, message: "No se pudo actualizar el estado" } } }
