import type { ModuleManifest } from "@/modules/manifest-types"

export const combustiblesModule = {
  id: "combustibles",
  permissions: [
    "combustibles:view",
    "combustibles:create",
    "combustibles:delete",
    "combustibles:import",
    "combustibles:sync_integrations",
    "combustibles:manage_integrations",
    "combustibles:revert",
    "combustibles:export",
    "combustibles:manage_vehicles",
    "combustibles:manage_suppliers",
    "combustibles:tae_view",
    "combustibles:tae_review",
    "combustibles:tae_manage_config",
    "combustibles:tae_import",
    "combustibles:tae_export",
    "combustibles:review_anomalies",
    "combustibles:resolve_anomalies",
    "combustibles:manage_anomaly_rules",
    "combustibles:view_audit",
    "combustibles:export_sensitive",
    "combustibles:view_costs",
    "combustibles:manage_statements",
  ] as const,

  permissionMeta: {
    "combustibles:view":             { id: "p-fuel-view",  description: "Ver dashboard de consumos de combustible" },
    "combustibles:create":           { id: "p-fuel-create", description: "Crear registros de combustible (facturas)" },
    "combustibles:delete":           { id: "p-fuel-delete", description: "Eliminar registros de combustible (facturas)" },
    "combustibles:import":           { id: "p-fuel-import", description: "Importar consumos de combustible por patente" },
    "combustibles:sync_integrations": { id: "p-fuel-sync-integrations", description: "Ejecutar sincronizaciones globales con proveedores de combustible" },
    "combustibles:manage_integrations": { id: "p-fuel-manage-integrations", description: "Administrar credenciales y configuración global de integraciones de combustible" },
    "combustibles:revert":           { id: "p-fuel-revert", description: "Revertir un lote de importación de consumos" },
    "combustibles:export":           { id: "p-fuel-export", description: "Exportar datos de combustible" },
    // Ya no cubre el padrón: eso es `admin:fleet_vehicles`. Lo que queda es la
    // decisión operativa sobre un equipo —sacarlo de servicio por un hallazgo,
    // vincular una patente de un lote importado—, que es de quien administra la
    // flota en terreno y no de quien mantiene el dato maestro.
    "combustibles:manage_vehicles":  { id: "p-fuel-veh",   description: "Decidir sobre un equipo en operación: sacarlo de servicio y vincular patentes de lotes importados" },
    "combustibles:manage_suppliers": { id: "p-fuel-sup",  description: "Gestionar proveedores de combustible" },
    "combustibles:tae_view":          { id: "p-fuel-tae-view", description: "Ver control operacional TAE" },
    "combustibles:tae_review":        { id: "p-fuel-tae-review", description: "Revisar cargas TAE" },
    "combustibles:tae_manage_config": { id: "p-fuel-tae-config", description: "Gestionar accesos y puntos TAE" },
    "combustibles:tae_import":        { id: "p-fuel-tae-import", description: "Importar histórico TAE" },
    "combustibles:tae_export":        { id: "p-fuel-tae-export", description: "Exportar control TAE" },
    "combustibles:review_anomalies":     { id: "p-fuel-anomaly-review", description: "Revisar, asignar y comentar casos de anomalía de combustible" },
    "combustibles:resolve_anomalies":    { id: "p-fuel-anomaly-resolve", description: "Resolver, descartar o reabrir casos de anomalía de combustible" },
    "combustibles:manage_anomaly_rules": { id: "p-fuel-anomaly-rules", description: "Configurar reglas de detección de anomalías de combustible" },
    "combustibles:view_audit":           { id: "p-fuel-audit-view", description: "Consultar historial de auditoría de combustible (valores anteriores/nuevos, actor, motivo)" },
    "combustibles:export_sensitive":     { id: "p-fuel-export-sensitive", description: "Exportar combustible con montos (IEC, IVA, total) — datos sensibles de costo" },
    "combustibles:view_costs":           { id: "p-fuel-view-costs", description: "Ver montos de combustible (facturas y reportes) — costo, no sólo consumo" },
    "combustibles:manage_statements":    { id: "p-fuel-manage-statements", description: "Crear estados de cuenta y registrar pagos de combustible" },
  },
  nav: [
    {
      areaId: "control-operacional",
      items: [
        {
          label: "Combustibles",
          href: "/combustibles",
          iconName: "GasPump",
          permissions: ["combustibles:view"],
        },
        {
          label: "Importar consumos",
          href: "/combustibles/importar",
          iconName: "Upload",
          permissions: ["combustibles:import"],
        },
        {
          label: "Bitácora general",
          href: "/combustibles/bitacora",
          iconName: "Books",
          permissions: ["combustibles:view"],
        },
        {
          label: "Análisis de rendimiento",
          href: "/combustibles/analisis",
          iconName: "ChartLineUp",
          permissions: ["combustibles:view"],
        },
        {
          label: "Control TAE",
          href: "/combustibles/tae",
          iconName: "QrCode",
          permissions: ["combustibles:tae_view"],
        },
      ],
    },
  ],
  defaultGrants: [
    { roleSlug: "administrador",  permission: "combustibles:view" },
    { roleSlug: "administrador",  permission: "combustibles:create" },
    { roleSlug: "administrador",  permission: "combustibles:delete" },
    { roleSlug: "administrador",  permission: "combustibles:import" },
    { roleSlug: "administrador",  permission: "combustibles:sync_integrations" },
    { roleSlug: "administrador",  permission: "combustibles:manage_integrations" },
    { roleSlug: "administrador",  permission: "combustibles:revert" },
    { roleSlug: "administrador",  permission: "combustibles:export" },
    { roleSlug: "administrador",  permission: "combustibles:manage_vehicles" },
    { roleSlug: "administrador",  permission: "combustibles:manage_suppliers" },
    { roleSlug: "administrador",  permission: "combustibles:tae_view" },
    { roleSlug: "administrador",  permission: "combustibles:tae_review" },
    { roleSlug: "administrador",  permission: "combustibles:tae_manage_config" },
    { roleSlug: "administrador",  permission: "combustibles:tae_import" },
    { roleSlug: "administrador",  permission: "combustibles:tae_export" },
    { roleSlug: "administrador",  permission: "combustibles:review_anomalies" },
    { roleSlug: "administrador",  permission: "combustibles:resolve_anomalies" },
    { roleSlug: "administrador",  permission: "combustibles:manage_anomaly_rules" },
    { roleSlug: "administrador",  permission: "combustibles:view_audit" },
    { roleSlug: "administrador",  permission: "combustibles:export_sensitive" },
    { roleSlug: "administrador",  permission: "combustibles:view_costs" },
    { roleSlug: "administrador",  permission: "combustibles:manage_statements" },
    { roleSlug: "jefa_chome",     permission: "combustibles:view" },
    { roleSlug: "jefa_chome",     permission: "combustibles:create" },
    { roleSlug: "jefa_chome",     permission: "combustibles:import" },
    { roleSlug: "jefa_chome",     permission: "combustibles:sync_integrations" },
    { roleSlug: "jefa_chome",     permission: "combustibles:manage_integrations" },
    { roleSlug: "jefa_chome",     permission: "combustibles:export" },
    { roleSlug: "jefa_chome",     permission: "combustibles:manage_vehicles" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_view" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_review" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_manage_config" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_import" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_export" },
    { roleSlug: "jefa_chome",     permission: "combustibles:review_anomalies" },
    { roleSlug: "jefa_chome",     permission: "combustibles:resolve_anomalies" },
    { roleSlug: "jefa_chome",     permission: "combustibles:view_audit" },
    { roleSlug: "jefa_chome",     permission: "combustibles:export_sensitive" },
    { roleSlug: "jefa_chome",     permission: "combustibles:view_costs" },
    { roleSlug: "jefa_chome",     permission: "combustibles:manage_statements" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:view" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:create" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:export" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:manage_vehicles" },
    { roleSlug: "solicitante_faena", permission: "combustibles:view" },
    { roleSlug: "solicitante_faena", permission: "combustibles:manage_vehicles" },
    { roleSlug: "prevencionista_faena", permission: "combustibles:view" },
    { roleSlug: "prevencionista_faena", permission: "combustibles:manage_vehicles" },
    { roleSlug: "admin_contrato", permission: "combustibles:view" },
    { roleSlug: "admin_contrato", permission: "combustibles:import" },
    { roleSlug: "admin_contrato", permission: "combustibles:revert" },
    { roleSlug: "admin_contrato", permission: "combustibles:manage_vehicles" },
  ],
} as const satisfies ModuleManifest
