import type { ModuleManifest } from "@/modules/manifest-types"

export const combustiblesModule = {
  id: "combustibles",
  permissions: [
    "combustibles:view",
    "combustibles:create",
    "combustibles:delete",
    "combustibles:import",
    "combustibles:revert",
    "combustibles:export",
    "combustibles:manage_vehicles",
    "combustibles:manage_suppliers",
    "combustibles:tae_view",
    "combustibles:tae_review",
    "combustibles:tae_manage_config",
    "combustibles:tae_import",
    "combustibles:tae_export",
  ] as const,

  permissionMeta: {
    "combustibles:view":             { id: "p-fuel-view",  description: "Ver dashboard de consumos de combustible" },
    "combustibles:create":           { id: "p-fuel-create", description: "Crear registros de combustible (facturas)" },
    "combustibles:delete":           { id: "p-fuel-delete", description: "Eliminar registros de combustible (facturas)" },
    "combustibles:import":           { id: "p-fuel-import", description: "Importar consumos de combustible por patente" },
    "combustibles:revert":           { id: "p-fuel-revert", description: "Revertir un lote de importación de consumos" },
    "combustibles:export":           { id: "p-fuel-export", description: "Exportar datos de combustible" },
    "combustibles:manage_vehicles":  { id: "p-fuel-veh",   description: "Gestionar vehículos de combustible" },
    "combustibles:manage_suppliers": { id: "p-fuel-sup",  description: "Gestionar proveedores de combustible" },
    "combustibles:tae_view":          { id: "p-fuel-tae-view", description: "Ver control operacional TAE" },
    "combustibles:tae_review":        { id: "p-fuel-tae-review", description: "Revisar cargas TAE" },
    "combustibles:tae_manage_config": { id: "p-fuel-tae-config", description: "Gestionar accesos y puntos TAE" },
    "combustibles:tae_import":        { id: "p-fuel-tae-import", description: "Importar histórico TAE" },
    "combustibles:tae_export":        { id: "p-fuel-tae-export", description: "Exportar control TAE" },
  },
  nav: [
    {
      areaId: "control-operacional",
      items: [
        {
          label: "Combustibles",
          href: "/combustibles",
          iconName: "GasPump",
          permissions: ["combustibles:view"],
        },
        {
          label: "Importar consumos",
          href: "/combustibles/importar",
          iconName: "Upload",
          permissions: ["combustibles:import"],
        },
        {
          label: "Control TAE",
          href: "/combustibles/tae",
          iconName: "QrCode",
          permissions: ["combustibles:tae_view"],
        },
      ],
    },
  ],
  defaultGrants: [
    { roleSlug: "administrador",  permission: "combustibles:view" },
    { roleSlug: "administrador",  permission: "combustibles:create" },
    { roleSlug: "administrador",  permission: "combustibles:delete" },
    { roleSlug: "administrador",  permission: "combustibles:import" },
    { roleSlug: "administrador",  permission: "combustibles:revert" },
    { roleSlug: "administrador",  permission: "combustibles:export" },
    { roleSlug: "administrador",  permission: "combustibles:manage_vehicles" },
    { roleSlug: "administrador",  permission: "combustibles:manage_suppliers" },
    { roleSlug: "administrador",  permission: "combustibles:tae_view" },
    { roleSlug: "administrador",  permission: "combustibles:tae_review" },
    { roleSlug: "administrador",  permission: "combustibles:tae_manage_config" },
    { roleSlug: "administrador",  permission: "combustibles:tae_import" },
    { roleSlug: "administrador",  permission: "combustibles:tae_export" },
    { roleSlug: "jefa_chome",     permission: "combustibles:view" },
    { roleSlug: "jefa_chome",     permission: "combustibles:create" },
    { roleSlug: "jefa_chome",     permission: "combustibles:import" },
    { roleSlug: "jefa_chome",     permission: "combustibles:export" },
    { roleSlug: "jefa_chome",     permission: "combustibles:manage_vehicles" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_view" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_review" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_manage_config" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_import" },
    { roleSlug: "jefa_chome",     permission: "combustibles:tae_export" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:view" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:create" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:export" },
    { roleSlug: "jefe_mantencion", permission: "combustibles:manage_vehicles" },
    { roleSlug: "solicitante_faena", permission: "combustibles:view" },
    { roleSlug: "solicitante_faena", permission: "combustibles:manage_vehicles" },
    { roleSlug: "prevencionista_faena", permission: "combustibles:view" },
    { roleSlug: "prevencionista_faena", permission: "combustibles:manage_vehicles" },
    { roleSlug: "admin_contrato", permission: "combustibles:view" },
    { roleSlug: "admin_contrato", permission: "combustibles:import" },
    { roleSlug: "admin_contrato", permission: "combustibles:revert" },
    { roleSlug: "admin_contrato", permission: "combustibles:manage_vehicles" },
  ],
} as const satisfies ModuleManifest
